//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galstars.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galstars.Extensions.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Account_0001&quot;: &quot;存档繼承&quot;,
        ///      &quot;Account_0002&quot;: &quot;請輸入繼承代碼&quot;,
        ///      &quot;Account_0003&quot;: &quot;※請確認輸入内容是否正確&quot;,
        ///      &quot;Account_0004&quot;: &quot;請選擇繼承方法&quot;,
        ///      &quot;Account_0005&quot;: &quot;請在之前使用的設備發行繼承代碼，\n以進行遊戲存档資料的繼承。&quot;,
        ///      &quot;Account_0006&quot;: &quot;請選擇外部連結進行認證，\n以繼承關聯的遊戲存档資料。&quot;,
        ///      &quot;Account_0007&quot;: &quot;輸入繼承代碼&quot;,
        ///      &quot;Account_0008&quot;: &quot;請輸入發送到祢登録的郵箱的繼承代碼。&quot;,
        ///      &quot;Account_0009&quot;: &quot;根據祢所輸入的繼承代碼，沒有找到相關遊戲存档資料。\n\n非常抱歉，請祢確認代碼是否正確之後再次嘗試。&quot;,
        ///      &quot;Account_0010&quot;: &quot;祢輸入的繼承代碼超過了有效期限。\n非常抱歉，請從[ffcd45]現在遊玩Shadowverse的設備[-]\n再次發行繼承代碼。&quot;,
        ///      &quot;Acco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountTextJson {
            get {
                return ResourceManager.GetString("AccountTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Arena_0001&quot;: &quot;競技場&quot;,
        ///      &quot;Arena_0002&quot;: &quot;雙選模式&quot;,
        ///      &quot;Arena_0003&quot;: &quot;關於雙選模式&quot;,
        ///      &quot;Arena_0015&quot;: &quot;期間&quot;,
        ///      &quot;Arena_0004&quot;: &quot;使用入場券&quot;,
        ///      &quot;Arena_0005&quot;: &quot;設定參加費用&quot;,
        ///      &quot;Arena_0006&quot;: &quot;將使用金幣\n或競技場入場券\n來作為參加費用&quot;,
        ///      &quot;Arena_0007&quot;: &quot;請選擇一個職業&quot;,
        ///      &quot;Arena_0008&quot;: &quot;選牌&quot;,
        ///      &quot;Arena_0009&quot;: &quot;確認牌組&quot;,
        ///      &quot;Arena_0010&quot;: &quot;牌組張數\n{0}/{1}&quot;,
        ///      &quot;Arena_0011&quot;: &quot;&quot;,
        ///      &quot;Arena_0012&quot;: &quot;還有{0}次&quot;,
        ///      &quot;Arena_0014&quot;: &quot;結束雙選模式獲得獎勵&quot;,
        ///      &quot;Arena_0016&quot;: &quot;對戰\n開始&quot;,
        ///      &quot;Arena_0017&quot;: &quot;現在獲得的獎勵&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArenaTextJson {
            get {
                return ResourceManager.GetString("ArenaTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Arena_Load_0001&quot;: &quot;雙選模式&quot;,
        ///      &quot;Arena_Load_0002&quot;: &quot;通過選擇15組牌來組成合計30張牌的牌組，\n並連續進行5場比賽來贏得祢的報酬。&quot;,
        ///      &quot;Arena_Load_0003&quot;: &quot;選擇參賽方式&quot;
        ///}.
        /// </summary>
        internal static string arenatextmaster {
            get {
                return ResourceManager.GetString("arenatextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Battle_keyword_Title_0001&quot;: &quot;啓言&quot;,
        ///      &quot;Battle_keyword_Title_0002&quot;: &quot;終語&quot;,
        ///      &quot;Battle_keyword_Title_0003&quot;: &quot;進化時&quot;,
        ///      &quot;Battle_keyword_Title_0004&quot;: &quot;攻撃時&quot;,
        ///      &quot;Battle_keyword_Title_0005&quot;: &quot;守護&quot;,
        ///      &quot;Battle_keyword_Title_0006&quot;: &quot;疾走&quot;,
        ///      &quot;Battle_keyword_Title_0007&quot;: &quot;潛伏&quot;,
        ///      &quot;Battle_keyword_Title_0008&quot;: &quot;必殺&quot;,
        ///      &quot;Battle_keyword_Title_0009&quot;: &quot;系命&quot;,
        ///      &quot;Battle_keyword_Title_0010&quot;: &quot;覺醒&quot;,
        ///      &quot;Battle_keyword_Title_0011&quot;: &quot;復仇&quot;,
        ///      &quot;Battle_keyword_Title_0012&quot;: &quot;共鳴&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string battlekeywordmaster {
            get {
                return ResourceManager.GetString("battlekeywordmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Battle_0004&quot;: &quot;雙選模式&quot;,
        ///      &quot;Battle_0001&quot;: &quot;自由匹配&quot;,
        ///      &quot;Battle_0002&quot;: &quot;天梯匹配&quot;,
        ///      &quot;Battle_0003&quot;: &quot;私人對戰&quot;,
        ///      &quot;Battle_0005&quot;: &quot;選擇牌組(自由匹配)&quot;,
        ///      &quot;Battle_0006&quot;: &quot;選擇牌組(天梯匹配)&quot;,
        ///      &quot;Battle_0007&quot;: &quot;選擇牌組(私人對戰)&quot;,
        ///      &quot;Battle_0008&quot;: &quot;匹配中&quot;,
        ///      &quot;Battle_0300&quot;: &quot;重新連接嘛？&quot;,
        ///      &quot;Battle_0301&quot;: &quot;重試&quot;,
        ///      &quot;Battle_0014&quot;: &quot;房間 ID {0}&quot;,
        ///      &quot;Battle_0013&quot;: &quot;進入房間&quot;,
        ///      &quot;Battle_0302&quot;: &quot;進入房間出錯&quot;,
        ///      &quot;Battle_0009&quot;: &quot;晉級戰&quot;,
        ///      &quot;Battle_0010&quot;: &quot;本次對戰勝利即可晉級&quot;,
        ///      &quot;Battle_0164&quot;: &quot;勝利！&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BattleTextJson {
            get {
                return ResourceManager.GetString("BattleTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;BT_100011010&quot;: &quot;&quot;,
        ///      &quot;BT_100011020&quot;: &quot;&quot;,
        ///      &quot;BT_100011030&quot;: &quot;&quot;,
        ///      &quot;BT_100011040&quot;: &quot;&quot;,
        ///      &quot;BT_100011050&quot;: &quot;&quot;,
        ///      &quot;BT_100012010&quot;: &quot;+1/+1&quot;,
        ///      &quot;BT_100031010&quot;: &quot;&quot;,
        ///      &quot;BT_100031020&quot;: &quot;&quot;,
        ///      &quot;BT_100111010&quot;: &quot;&quot;,
        ///      &quot;BT_100111020&quot;: &quot;&quot;,
        ///      &quot;BT_100111030&quot;: &quot;+1/+0&quot;,
        ///      &quot;BT_100111040&quot;: &quot;+1/+1，[ffcd45]守護[-]&quot;,
        ///      &quot;BT_100111050&quot;: &quot;+2/+2&quot;,
        ///      &quot;BT_100111060&quot;: &quot;&quot;,
        ///      &quot;BT_100111070&quot;: &quot;&quot;,
        ///      &quot;BT_100114010&quot;: &quot;&quot;,
        ///      &quot;BT_100121010&quot;: &quot;+1/+1&quot;,
        ///      &quot;BT_1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bufftextmaster {
            get {
                return ResourceManager.GetString("bufftextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;BDPN_構築済みデッキ1弾_エルフ&quot;: &quot;白銀射手(精靈)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ロイヤル&quot;: &quot;盛宴開場(皇室護衛)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ウィッチ&quot;: &quot;法神降臨(巫師)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ドラゴン&quot;: &quot;闇黑竜騎(竜)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ネクロマンサー&quot;: &quot;冥炎咆哮(死靈術士)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ヴァンパイア&quot;: &quot;女王之吻(吸血鬼)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ビショップ&quot;: &quot;聖潔戰場(主教)&quot;,
        ///      &quot;BDPN_構築済みデッキ2弾_エルフ&quot;: &quot;異形之棘(精靈)&quot;,
        ///      &quot;BDPN_構築済みデッキ2弾_ロイヤル&quot;: &quot;疾風迅雷(皇室護衛)&quot;,
        ///      &quot;BDPN_構築済みデッキ2弾_ウィッチ&quot;: &quot;暴威魔能(巫師)&quot;,
        ///      &quot;BDPN_構築済みデッキ2弾_ドラゴン&quot;: &quot;水竜加護(竜)&quot;,
        ///      &quot;BDPN_構築済みデッキ2弾_ネクロマンサー&quot;: &quot;靈魂主宰( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string builddeckproducttextmaster {
            get {
                return ResourceManager.GetString("builddeckproducttextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;BDSSN_構築済みデッキ1弾&quot;: &quot;BDSSN_構築済みデッキ1弾&quot;,
        ///      &quot;BDSI_構築済みデッキ1弾&quot;: &quot;各套擁有1張限定版插畫的豪華傳説牌（無法分解）。\n毎套可購買3次，根據購買次數價格會發生變化。\n初次：水晶500個，之後：水晶750個。&quot;,
        ///      &quot;BDSSN_構築済みデッキ2弾&quot;: &quot;BDSSN_構築済みデッキ2弾&quot;,
        ///      &quot;BDSI_構築済みデッキ2弾&quot;: &quot;各套擁有1張限定版插畫的豪華傳説牌（無法分解）。\n毎套可購買3次，根據購買次數價格會發生變化。\n初次：水晶500個，之後：水晶750個。&quot;
        ///}.
        /// </summary>
        internal static string builddeckseriestextmaster {
            get {
                return ResourceManager.GetString("builddeckseriestextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;CN_100011010&quot;: &quot;地精戰士&quot;,
        ///      &quot;CN_100011020&quot;: &quot;格鬥士&quot;,
        ///      &quot;CN_101011010&quot;: &quot;牛頭怪&quot;,
        ///      &quot;CN_101011020&quot;: &quot;沙漠騎手&quot;,
        ///      &quot;CN_100011030&quot;: &quot;流浪傭兵&quot;,
        ///      &quot;CN_100011040&quot;: &quot;巨兵衛&quot;,
        ///      &quot;CN_100011050&quot;: &quot;天劍神女&quot;,
        ///      &quot;CN_101011030&quot;: &quot;執盾天使&quot;,
        ///      &quot;CN_100031010&quot;: &quot;囚罪雙子・烈焰&quot;,
        ///      &quot;CN_100031020&quot;: &quot;囚罪雙子・琉璃&quot;,
        ///      &quot;CN_101021010&quot;: &quot;聖鈴天使&quot;,
        ///      &quot;CN_101021020&quot;: &quot;蜥蜴怪人&quot;,
        ///      &quot;CN_101011040&quot;: &quot;愈光天使&quot;,
        ///      &quot;CN_101021030&quot;: &quot;英雄王・吉爾伽美什&quot;,
        ///      &quot;CN_101021040&quot;: &quot;地精惡魔騎手&quot;,
        ///      &quot;CN_101031010&quot;: &quot;命運之末・烏露德&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cardnametextmaster {
            get {
                return ResourceManager.GetString("cardnametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;90000_long&quot;: &quot;代幣&quot;,
        ///      &quot;90000_short&quot;: &quot;TKN&quot;,
        ///      &quot;10000_long&quot;: &quot;基本&quot;,
        ///      &quot;10000_short&quot;: &quot;BSC&quot;,
        ///      &quot;10001_long&quot;: &quot;標準&quot;,
        ///      &quot;10001_short&quot;: &quot;STD&quot;,
        ///      &quot;10002_long&quot;: &quot;黑闇進化&quot;,
        ///      &quot;10002_short&quot;: &quot;DRK&quot;,
        ///      &quot;10003_long&quot;: &quot;巴哈姆特降臨&quot;,
        ///      &quot;10003_short&quot;: &quot;ROB&quot;,
        ///      &quot;10004_long&quot;: &quot;諸神狂嵐&quot;,
        ///      &quot;10004_short&quot;: &quot;TOG&quot;,
        ///      &quot;10005_long&quot;: &quot;夢境奇想&quot;,
        ///      &quot;10005_short&quot;: &quot;WLD&quot;
        ///}.
        /// </summary>
        internal static string cardsetnametextmaster {
            get {
                return ResourceManager.GetString("cardsetnametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Card_0001&quot;: &quot;牌組清單&quot;,
        ///      &quot;Card_0002&quot;: &quot;默認牌組&quot;,
        ///      &quot;Card_0004&quot;: &quot;默認&quot;,
        ///      &quot;Card_0005&quot;: &quot;牌櫃&quot;,
        ///      &quot;Card_0006&quot;: &quot;使用[ffca45]{0}[-]&quot;,
        ///      &quot;Card_0007&quot;: &quot;編輯牌組&quot;,
        ///      &quot;Card_0042&quot;: &quot;編輯牌組&quot;,
        ///      &quot;Card_0008&quot;: &quot;刪除牌組&quot;,
        ///      &quot;Card_0009&quot;: &quot;確定刪除牌組嘛？&quot;,
        ///      &quot;Card_0010&quot;: &quot;牌組已刪除。&quot;,
        ///      &quot;Card_0011&quot;: &quot;牌組名&quot;,
        ///      &quot;Card_0012&quot;: &quot;請輸入牌組名。&quot;,
        ///      &quot;Card_0014&quot;: &quot;名稱已變更。&quot;,
        ///      &quot;Card_0018&quot;: &quot;保存&quot;,
        ///      &quot;Card_0019&quot;: &quot;牌組已保存。&quot;,
        ///      &quot;Card_0015&quot;: &quot;變更牌背&quot;,
        ///      &quot;Card_0016&quot;: &quot;把牌組{0}的牌背變更為{1}嘛？&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CardTextJson {
            get {
                return ResourceManager.GetString("CardTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;CC_アリサ&quot;: &quot;亞里莎&quot;,
        ///      &quot;CC_エリカ&quot;: &quot;艾莉華&quot;,
        ///      &quot;CC_イザベル&quot;: &quot;伊莎貝爾&quot;,
        ///      &quot;CC_ローウェン&quot;: &quot;羅文&quot;,
        ///      &quot;CC_ルナ&quot;: &quot;露娜&quot;,
        ///      &quot;CC_ユリアス&quot;: &quot;尤里亞斯&quot;,
        ///      &quot;CC_イリス&quot;: &quot;伊莉絲&quot;,
        ///      &quot;CC_ネクサス&quot;: &quot;涅墨西斯&quot;,
        ///      &quot;CC_ロザリア&quot;: &quot;蘿沙麗亞&quot;,
        ///      &quot;CC_虚の影アリサ&quot;: &quot;虚之影 亞里莎&quot;,
        ///      &quot;CC_虚の影エリカ&quot;: &quot;虚之影 艾莉華&quot;,
        ///      &quot;CC_虚の影イザベル&quot;: &quot;虚之影 伊莎貝爾&quot;,
        ///      &quot;CC_虚の影ローウェン&quot;: &quot;虚之影 羅文&quot;,
        ///      &quot;CC_虚の影ルナ&quot;: &quot;虚之影 露娜&quot;,
        ///      &quot;CC_虚の影ユリアス&quot;: &quot;虚之影 尤里亞斯&quot;,
        ///      &quot;CC_虚の影イリス&quot;: &quot;虚之影 伊莉絲&quot;,
        ///      &quot;CC_黒龍&quot;: &quot;黑龍&quot;,
        ///      &quot;CC_虚の影&quot;: &quot;虚之影&quot;,
        ///      &quot;CC_虚の影2&quot;: &quot;虚之 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string classcharanametextmaster {
            get {
                return ResourceManager.GetString("classcharanametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Common_0105&quot;: &quot;精靈&quot;,
        ///      &quot;Common_0106&quot;: &quot;皇室護衛&quot;,
        ///      &quot;Common_0107&quot;: &quot;巫師&quot;,
        ///      &quot;Common_0108&quot;: &quot;竜&quot;,
        ///      &quot;Common_0109&quot;: &quot;死靈術士&quot;,
        ///      &quot;Common_0110&quot;: &quot;吸血鬼&quot;,
        ///      &quot;Common_0111&quot;: &quot;主教&quot;
        ///}.
        /// </summary>
        internal static string classnametextmaster {
            get {
                return ResourceManager.GetString("classnametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;clan_0&quot;: &quot;中立&quot;,
        ///      &quot;clan_1&quot;: &quot;精靈&quot;,
        ///      &quot;clan_2&quot;: &quot;皇室護衛&quot;,
        ///      &quot;clan_3&quot;: &quot;巫師&quot;,
        ///      &quot;clan_4&quot;: &quot;竜&quot;,
        ///      &quot;clan_5&quot;: &quot;死靈術士&quot;,
        ///      &quot;clan_6&quot;: &quot;吸血鬼&quot;,
        ///      &quot;clan_7&quot;: &quot;主教&quot;
        ///}.
        /// </summary>
        internal static string classtextjson {
            get {
                return ResourceManager.GetString("classtextjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Common_0001&quot;: &quot;是&quot;,
        ///      &quot;Common_0002&quot;: &quot;否&quot;,
        ///      &quot;Common_0003&quot;: &quot;決定&quot;,
        ///      &quot;Common_0004&quot;: &quot;確認&quot;,
        ///      &quot;Common_0053&quot;: &quot;取消&quot;,
        ///      &quot;Common_0005&quot;: &quot;取消&quot;,
        ///      &quot;Common_0008&quot;: &quot;關閉&quot;,
        ///      &quot;Common_0009&quot;: &quot;點撃&quot;,
        ///      &quot;Common_0021&quot;: &quot;資訊&quot;,
        ///      &quot;Common_0022&quot;: &quot;詳細&quot;,
        ///      &quot;Common_0026&quot;: &quot;輸入&quot;,
        ///      &quot;Common_0036&quot;: &quot;情報&quot;,
        ///      &quot;Common_0042&quot;: &quot;下一級&quot;,
        ///      &quot;Common_0043&quot;: &quot;下一等級&quot;,
        ///      &quot;Common_0045&quot;: &quot;等級&quot;,
        ///      &quot;Common_0046&quot;: &quot;對戰等級&quot;,
        ///      &quot;Common_0047&quot;: &quot;對戰積分&quot;,
        ///      &quot;Common_0048&quot;: &quot;大師賽積分&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonTextJson {
            get {
                return ResourceManager.GetString("CommonTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Country_Category_Asia&quot;: &quot;亞洲&quot;,
        ///      &quot;Country_Category_Europe&quot;: &quot;歐洲&quot;,
        ///      &quot;Country_Category_Americas&quot;: &quot;北美及中南美&quot;,
        ///      &quot;Country_Category_Oceania&quot;: &quot;大洋洲&quot;,
        ///      &quot;Country_Category_Africa&quot;: &quot;非洲&quot;
        ///}.
        /// </summary>
        internal static string countrytextmaster {
            get {
                return ResourceManager.GetString("countrytextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;DEG_私だって戦えるんだから！&quot;: &quot;就算是我也會戰斗！&quot;,
        ///      &quot;DEG_妖精少女&quot;: &quot;精靈少女&quot;,
        ///      &quot;DEG_約束の弓 誓いの矢&quot;: &quot;約定之弓 誓言之矢&quot;,
        ///      &quot;DEG_Elf Master&quot;: &quot;大師級精靈&quot;,
        ///      &quot;DEG_ここで死んで頂きます&quot;: &quot;請葬身於此罷&quot;,
        ///      &quot;DEG_メイドが本業&quot;: &quot;女仆是本職&quot;,
        ///      &quot;DEG_Save the Queen &quot;: &quot;拯救女皇&quot;,
        ///      &quot;DEG_Royal Master&quot;: &quot;大師級皇室護衛&quot;,
        ///      &quot;DEG_手加減なしよ、本気で行くわ！&quot;: &quot;我可不會手下留情！&quot;,
        ///      &quot;DEG_天才錬金術師&quot;: &quot;天才煉金術士&quot;,
        ///      &quot;DEG_禁忌の探求者&quot;: &quot;禁忌的探求者&quot;,
        ///      &quot;DEG_Witch Master&quot;: &quot;大師級巫師&quot;,
        ///      &quot;DEG_この俺が相手だ！&quot;: &quot;我來做祢的對手！&quot;,
        ///      &quot;DEG_歴代最強竜騎士&quot;: &quot;歴代最強竜騎士&quot;,
        ///      &quot;DEG_咎負いし黒龍騎士&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string degreetextmaster {
            get {
                return ResourceManager.GetString("degreetextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Dialog_Text_Alignment&quot;: &quot;Center&quot;,
        ///      &quot;Dia_Battle_001_Title&quot;: &quot;回合結束&quot;,
        ///      &quot;Dia_Battle_001_Button&quot;: &quot;結束&quot;,
        ///      &quot;Dia_Battle_002_Title&quot;: &quot;進化&quot;,
        ///      &quot;Dia_Battle_002_Button&quot;: &quot;進化&quot;,
        ///      &quot;Dia_Battle_003_Button&quot;: &quot;棄權&quot;,
        ///      &quot;Dia_Battle_003_Button_2&quot;: &quot;結束&quot;,
        ///      &quot;Dia_Result_001_Button&quot;: &quot;報告&quot;,
        ///      &quot;Dia_Tutorial_001_Button&quot;: &quot;跳過&quot;,
        ///      &quot;Dia_Title_001_Button&quot;: &quot;完成&quot;,
        ///      &quot;Dia_Title_002_Button&quot;: &quot;結束&quot;,
        ///      &quot;Dia_Web_001_Button&quot;: &quot;打開&quot;,
        ///      &quot;Dia_ChapterSelect_001_Button&quot;: &quot;開始&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DialogTextJson {
            get {
                return ResourceManager.GetString("DialogTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;EM_シャドウバース&quot;: &quot;闇影詩章&quot;,
        ///      &quot;EM_アリサ&quot;: &quot;亞里莎&quot;,
        ///      &quot;EM_エリカ&quot;: &quot;艾莉華&quot;,
        ///      &quot;EM_イザベル&quot;: &quot;伊莎貝爾&quot;,
        ///      &quot;EM_ローウェン&quot;: &quot;羅文&quot;,
        ///      &quot;EM_ルナ&quot;: &quot;露娜&quot;,
        ///      &quot;EM_ユリアス&quot;: &quot;尤里亞斯&quot;,
        ///      &quot;EM_イリス&quot;: &quot;伊莉絲&quot;,
        ///      &quot;EM_セルウィン&quot;: &quot;箭神・塞爾温&quot;,
        ///      &quot;EM_レイサム&quot;: &quot;無畏先鋒・萊瑟姆&quot;,
        ///      &quot;EM_エラスムス&quot;: &quot;大召喚師・伊拉斯謨&quot;,
        ///      &quot;EM_フォルテ&quot;: &quot;黑竜戰騎・法露特&quot;,
        ///      &quot;EM_モルディカイ&quot;: &quot;決死者・莫迪凱&quot;,
        ///      &quot;EM_ヴァンピィ&quot;: &quot;吸血姫・斑比&quot;,
        ///      &quot;EM_ガルラ&quot;: &quot;天煌守護者・迦樓羅&quot;,
        ///      &quot;EM_ルシフェル&quot;: &quot;晨星天使・路西法&quot;,
        ///      &quot;EM_アテナ&quot;: &quot;知惠神・雅典娜&quot;,
        ///      &quot;EM_ファイター&quot;: &quot;格斗士&quot;,
        ///      &quot;EM_ローズ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emblemtextmaster {
            get {
                return ResourceManager.GetString("emblemtextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;ET_AI_01001_000_101&quot;: &quot;真不錯阿！&quot;,
        ///      &quot;ET_AI_01001_000_102&quot;: &quot;這一招不錯罷？&quot;,
        ///      &quot;ET_AI_01001_000_111&quot;: &quot;完蛋拉！&quot;,
        ///      &quot;ET_AI_01001_000_121&quot;: &quot;怎麼會這樣...&quot;,
        ///      &quot;ET_AI_01001_000_131&quot;: &quot;我放棄了～&quot;,
        ///      &quot;ET_AI_01001_000_141&quot;: &quot;來罷！&quot;,
        ///      &quot;ET_AI_01001_000_142&quot;: &quot;可別嚇得逃跑哦！&quot;,
        ///      &quot;ET_AI_01001_000_151&quot;: &quot;哈阿???。&quot;,
        ///      &quot;ET_AI_01001_000_152&quot;: &quot;恩...&quot;,
        ///      &quot;ET_AI_01001_000_161&quot;: &quot;祢還好罷？&quot;,
        ///      &quot;ET_AI_01001_000_162&quot;: &quot;確定要這樣麼？&quot;,
        ///      &quot;ET_AI_01001_000_191&quot;: &quot;打得漂亮！&quot;,
        ///      &quot;ET_AI_01001_000_192&quot;: &quot;欸欸!? [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emotetextmaster {
            get {
                return ResourceManager.GetString("emotetextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;ErrorHeader_DEFAULT&quot;: &quot;出錯&quot;,
        ///      &quot;ErrorHeader_0001&quot;: &quot;出錯&quot;,
        ///      &quot;ErrorHeader_0002&quot;: &quot;出錯&quot;,
        ///      &quot;ErrorHeader_0003&quot;: &quot;出錯&quot;,
        ///      &quot;ErrorHeader_0004&quot;: &quot;出錯&quot;,
        ///      &quot;ErrorHeader_0005&quot;: &quot;系統維護中&quot;,
        ///      &quot;ErrorHeader_0006&quot;: &quot;超時&quot;,
        ///      &quot;ErrorHeader_0009&quot;: &quot;繼承失敗&quot;,
        ///      &quot;ErrorHeader_0010&quot;: &quot;繼承失敗&quot;,
        ///      &quot;ErrorHeader_0011&quot;: &quot;繼承失敗&quot;,
        ///      &quot;ErrorHeader_0012&quot;: &quot;網路連接出錯&quot;,
        ///      &quot;ErrorHeader_0007&quot;: &quot;輸入出錯&quot;,
        ///      &quot;ErrorHeader_0008&quot;: &quot;輸入出錯&quot;,
        ///      &quot;ErrorHeader_0013&quot;: &quot;下載數據&quot;,
        ///      &quot;ErrorHeader_0014&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorHeaderTextJson {
            get {
                return ResourceManager.GetString("ErrorHeaderTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Error_DEFAULT&quot;: &quot;發生錯誤。\n如果問題無法解決，\n煩請附上錯誤代碼進行諮詢。\n(錯誤代碼{0})&quot;,
        ///      &quot;Error_0001&quot;: &quot;錯誤&quot;,
        ///      &quot;Error_0002&quot;: &quot;錯誤&quot;,
        ///      &quot;Error_0003&quot;: &quot;出錯了&quot;,
        ///      &quot;Error_0004&quot;: &quot;{0}出錯了。&quot;,
        ///      &quot;Error_0005&quot;: &quot;系統維護中。\n\n在維護結束之前，請祢耐心等待。&quot;,
        ///      &quot;Error_0006&quot;: &quot;超時了。&quot;,
        ///      &quot;Error_0009&quot;: &quot;繼承失敗了。\n(錯誤代碼：9)&quot;,
        ///      &quot;Error_0010&quot;: &quot;繼承的設定失敗了。\n(錯誤代碼：10)&quot;,
        ///      &quot;Error_0011&quot;: &quot;存档的繼承失敗了。\n(錯誤代碼：11)&quot;,
        ///      &quot;Error_0012&quot;: &quot;網路連接發生錯誤。\n\n請確認網路連接状況後重試。\n&quot;,
        ///      &quot;Error_0007&quot;: &quot;超出字數限制或使用了禁止使用的字詞。&quot;,
        ///      &quot;Error_0008&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorTextJson {
            get {
                return ResourceManager.GetString("ErrorTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;FirstTips_0001&quot;: &quot;一套牌組由40張牌構成。\n在編輯牌組畫面，\n向上拉動可以設定想使用的牌。\n移除時則向下拉動牌。&quot;,
        ///      &quot;FirstTips_0002&quot;: &quot;製作牌時需要紅色乙太。\n紅色乙太可以在遊戲中通過報酬獲取\n或分解牌來入手。&quot;,
        ///      &quot;FirstTips_0003&quot;: &quot;如果要製作1張自己沒有的牌，\n可以選擇「製作」來消耗紅色乙太來入手。\n(也有無法製作或分解的牌。)&quot;,
        ///      &quot;FirstTips_0004&quot;: &quot;雙選模式是指反復從隨機出現的備選牌中選取\n以組成隨機的牌組來進行對戰的模式。\n勝場越多，報酬越豐厚。&quot;,
        ///      &quot;FirstTips_0005&quot;: &quot;歡迎來到Shadowverse的世界。\n教程中獲得的報酬可以隨時在「禮物」中領取。&quot;,
        ///      &quot;FirstTips_0006&quot;: &quot;可以首先選擇「單人」進行遊戲。\n在單人模式中，與AI的對戰獲勝後，\n作為報酬，可獲得各種各樣的牌。&quot;,
        ///      &quot;FirstTips_0007&quot;: &quot;通過對戰勝利，可以獲得只能在劇情裡入手的強力牌。&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstTipsJson {
            get {
                return ResourceManager.GetString("FirstTipsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;FT_100011010_01&quot;: &quot;外表看起來稍微有點讓人吃驚，但是其實沒有什麼了不起的。總之只是魔族的底層，即沒有力量，也沒有智慧。但是，還是要注意「狗急也會跳牆」。&quot;,
        ///      &quot;FT_100011010_02&quot;: &quot;稍微有點經驗的人，就沒必要害怕這種最低級的魔物。話雖如此，還是要注意武裝了的它們。就算是窮酸可憐的小劍，被撃中了還是會流血的。&quot;,
        ///      &quot;FT_100011020_01&quot;: &quot;如果説在這充滿紛爭的世界有能依靠的東西，那就是自己的力量。所以我會一直勝利。一定會！&quot;,
        ///      &quot;FT_100011020_02&quot;: &quot;如果説在這充滿紛爭的世界有能依靠的東西，那就是自己的力量。用這把劍開創的未來，就是我所追求的東西。&quot;,
        ///      &quot;FT_100011030_01&quot;: &quot;撃退魔怪的委託？報酬當然會很多罷？如果得該得到的東西的話，會有超過期待的成果哦。&quot;,
        ///      &quot;FT_100011030_02&quot;: &quot;我會按照收到的報酬好好工作。絶對是一分錢，一分成果。這就是我的原則。那麼，就開始工作罷……魔怪們！快來受死！祢們的性命，就是我明天的食糧！&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string flavourtextmaster {
            get {
                return ResourceManager.GetString("flavourtextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;IT_1&quot;: &quot;競技場入場券&quot;,
        ///      &quot;IT_1000&quot;: &quot;次元石&quot;,
        ///      &quot;IT_10001&quot;: &quot;標準牌包兌換券&quot;,
        ///      &quot;IT_10002&quot;: &quot;黑闇進化牌包兌換券&quot;,
        ///      &quot;IT_10003&quot;: &quot;巴哈姆特降臨牌包兌換券&quot;,
        ///      &quot;IT_10004&quot;: &quot;諸神狂嵐牌包兌換券&quot;,
        ///      &quot;IT_10005&quot;: &quot;夢境奇想牌包兌換券&quot;,
        ///      &quot;IT_10006&quot;: &quot;新牌包兌換券&quot;
        ///}.
        /// </summary>
        internal static string itemtextmaster {
            get {
                return ResourceManager.GetString("itemtextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;LSPPN_神撃のバハムート_1&quot;: &quot;箭神・塞爾温&quot;,
        ///      &quot;LSPPN_神撃のバハムート_2&quot;: &quot;無畏先鋒・萊瑟姆&quot;,
        ///      &quot;LSPPN_神撃のバハムート_3&quot;: &quot;大召喚師・伊拉斯謨&quot;,
        ///      &quot;LSPPN_神撃のバハムート_4&quot;: &quot;黑竜戰騎・法露特&quot;,
        ///      &quot;LSPPN_神撃のバハムート_5&quot;: &quot;決死者・莫迪凱&quot;,
        ///      &quot;LSPPN_神撃のバハムート_6&quot;: &quot;吸血姫・斑比&quot;,
        ///      &quot;LSPPN_神撃のバハムート_7&quot;: &quot;天煌守護者・迦樓羅&quot;,
        ///      &quot;LSPPN_SF5_1&quot;: &quot;嘉米懷特&quot;,
        ///      &quot;LSPPN_SF5_2&quot;: &quot;春麗&quot;,
        ///      &quot;LSPPN_SF5_3&quot;: &quot;韓蛛俐&quot;,
        ///      &quot;LSPPN_SF5_4&quot;: &quot;隆&quot;,
        ///      &quot;LSPPN_SF5_5&quot;: &quot;維加&quot;,
        ///      &quot;LSPPN_SF5_6&quot;: &quot;巴羅克&quot;,
        ///      &quot;LSPPN_SF5_7&quot;: &quot;神月凱琳&quot;,
        ///      &quot;LSPI_神撃のバハムート_1&quot;: &quot;他是身經百戰的獵人，\n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leaderskinproducttextmaster {
            get {
                return ResourceManager.GetString("leaderskinproducttextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;LSSI_神撃のバハムート&quot;: &quot;巴哈姆特之怒皮膚。\n\n祢可以在個人資料介面切換皮膚。&quot;,
        ///      &quot;LSSSN_神撃のバハムート&quot;: &quot;巴哈姆特之怒皮膚包&quot;,
        ///      &quot;LSSI_SF5&quot;: &quot;快打旋風5皮膚。\n\n祢可以在個人資料介面切換皮膚。&quot;,
        ///      &quot;LSSSN_SF5&quot;: &quot;快打旋風5皮膚包&quot;
        ///}.
        /// </summary>
        internal static string leaderskinseriestextmaster {
            get {
                return ResourceManager.GetString("leaderskinseriestextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Load_0001&quot;: &quot;正在下載最新資料           &quot;,
        ///      &quot;Load_0002&quot;: &quot;請在網路状況良好的状態下進行下載。\n(根據網路連接状況，可能會花費較長時間)&quot;,
        ///      &quot;Load_0003&quot;: &quot;亞里莎&quot;,
        ///      &quot;Load_0004&quot;: &quot;艾莉華&quot;,
        ///      &quot;Load_0005&quot;: &quot;伊莎貝爾&quot;,
        ///      &quot;Load_0006&quot;: &quot;羅文&quot;,
        ///      &quot;Load_0007&quot;: &quot;露娜&quot;,
        ///      &quot;Load_0008&quot;: &quot;尤里亞斯&quot;,
        ///      &quot;Load_0009&quot;: &quot;伊莉絲&quot;,
        ///      &quot;Load_0010&quot;: &quot;為了成為合格的森林守護者，\n毎天都在努力修行的精靈少女。\n為了救回被不明身分的家夥\n奪走的好友而踏上了旅途。&quot;,
        ///      &quot;Load_0011&quot;: &quot;阿雷斯達王國公主的女僕。\n不僅僅是作為女僕，在護衛方面也具有極高的能力。\n為了調査傳説的吸血鬼長眠的「封印的古城」\n發生的異状而從王城出發了。&quot;,
        ///      &quot;Load_0012&quot;: &quot;阿雷斯達王國進行魔法研究的\n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadTextJson {
            get {
                return ResourceManager.GetString("LoadTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;LoginBonus_0001&quot;: &quot;已獲得&quot;,
        ///      &quot;LoginBonus_0002&quot;: &quot;下回獲得 : {0}×{1}&quot;,
        ///      &quot;LoginBonus_0003&quot;: &quot;活動期間 : {0}&quot;,
        ///      &quot;LoginBonus_0004&quot;: &quot;NEXT&quot;
        ///}.
        /// </summary>
        internal static string LoginBonusJson {
            get {
                return ResourceManager.GetString("LoginBonusJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Mail_0001&quot;: &quot;郵件&quot;,
        ///      &quot;Mail_0002&quot;: &quot;禮物&quot;,
        ///      &quot;Mail_0003&quot;: &quot;邀請&quot;,
        ///      &quot;Mail_0025&quot;: &quot;刪除&quot;,
        ///      &quot;Mail_0004&quot;: &quot;全部領取&quot;,
        ///      &quot;Mail_0005&quot;: &quot;全部刪除&quot;,
        ///      &quot;Mail_0017&quot;: &quot;全部領取嘛？&quot;,
        ///      &quot;Mail_0018&quot;: &quot;全部刪除嘛？&quot;,
        ///      &quot;Mail_0009&quot;: &quot;收取郵件&quot;,
        ///      &quot;Mail_0010&quot;: &quot;刪除郵件&quot;,
        ///      &quot;Mail_0011&quot;: &quot;領取全部禮物&quot;,
        ///      &quot;Mail_0012&quot;: &quot;刪除全部郵件&quot;,
        ///      &quot;Mail_0015&quot;: &quot;收取{0}嘛？&quot;,
        ///      &quot;Mail_0016&quot;: &quot;刪除{0}嘛？&quot;,
        ///      &quot;Mail_0019&quot;: &quot;沒有可收取的郵件&quot;,
        ///      &quot;Mail_0020&quot;: &quot;沒有可刪除的郵件&quot;,
        ///      &quot;Mail_0006&quot;: &quot;已經領取所有禮物&quot;,
        ///      &quot;Mail_000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailTextJson {
            get {
                return ResourceManager.GetString("MailTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Mission_0001&quot;: &quot;任務&quot;,
        ///      &quot;Mission_0003&quot;: &quot;任務詳細内容&quot;,
        ///      &quot;Mission_0002&quot;: &quot;成就&quot;,
        ///      &quot;Mission_0007&quot;: &quot;成就詳細内容&quot;,
        ///      &quot;Mission_0008&quot;: &quot;解鎖&quot;,
        ///      &quot;Mission_0005&quot;: &quot;解鎖新的任務欄&quot;,
        ///      &quot;Mission_0004&quot;: &quot;解鎖追加欄&quot;,
        ///      &quot;Mission_0006&quot;: &quot;因已經達到可接受任務的數量上限，購買[ffca45]{0}[-]個追加任務欄嘛？&quot;,
        ///      &quot;Mission_0009&quot;: &quot;報酬：&quot;,
        ///      &quot;Mission_0010&quot;: &quot;未達成&quot;,
        ///      &quot;Mission_0011&quot;: &quot;達成率&quot;,
        ///      &quot;Mission_0012&quot;: &quot;完成&quot;,
        ///      &quot;Mission_0013&quot;: &quot;請到任務介面\n領取報酬。&quot;,
        ///      &quot;Mission_0014&quot;: &quot;報酬：{0}ｘ{1}個&quot;,
        ///      &quot;Mission_0015&quot;: &quot;放棄&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MissionTextJson {
            get {
                return ResourceManager.GetString("MissionTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;MyPage_0001&quot;: &quot;主介面&quot;,
        ///      &quot;MyPage_0002&quot;: &quot;單人&quot;,
        ///      &quot;MyPage_0003&quot;: &quot;對戰&quot;,
        ///      &quot;MyPage_0004&quot;: &quot;競技場&quot;,
        ///      &quot;MyPage_0005&quot;: &quot;收藏&quot;,
        ///      &quot;MyPage_0006&quot;: &quot;商店&quot;,
        ///      &quot;MyPage_0007&quot;: &quot;其它&quot;,
        ///      &quot;MyPage_0008&quot;: &quot;劇情模式&quot;,
        ///      &quot;MyPage_0009&quot;: &quot;練習模式&quot;,
        ///      &quot;MyPage_0010&quot;: &quot;自由匹配&quot;,
        ///      &quot;MyPage_0011&quot;: &quot;天梯匹配&quot;,
        ///      &quot;MyPage_0012&quot;: &quot;私人對戰&quot;,
        ///      &quot;MyPage_0013&quot;: &quot;雙選模式&quot;,
        ///      &quot;MyPage_0014&quot;: &quot;編輯牌組&quot;,
        ///      &quot;MyPage_0015&quot;: &quot;牌一覽/製作&quot;,
        ///      &quot;MyPage_0016&quot;: &quot;購買牌包&quot;,
        ///      &quot;MyPage_0017&quot;: &quot;購買禮包&quot;,
        ///      &quot;My [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MyPageTextJson {
            get {
                return ResourceManager.GetString("MyPageTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherCode_0005&quot;: &quot;輸入兌換碼&quot;,
        ///      &quot;OtherCode_0007&quot;: &quot;兌換記録&quot;,
        ///      &quot;OtherCode_0001&quot;: &quot;輸入兌換碼可以領取特典。\n獲得的特典會直接發送至「禮物」内。&quot;,
        ///      &quot;OtherCode_0003&quot;: &quot;※請不要輸入“-”&quot;,
        ///      &quot;OtherCode_0004&quot;: &quot;1個兌換碼只能使用1次。&quot;,
        ///      &quot;OtherCode_0006&quot;: &quot;標題&quot;,
        ///      &quot;OtherCode_0008&quot;: &quot;領取日期&quot;,
        ///      &quot;OtherCode_0009&quot;: &quot;請輸入代碼&quot;,
        ///      &quot;OtherCode_0010&quot;: &quot;代碼録入完畢。\n獲得的禮品會直接發送至「禮物」内。&quot;,
        ///      &quot;OtherCode_0011&quot;: &quot;録入完畢&quot;
        ///}.
        /// </summary>
        internal static string OtherCodeTextJson {
            get {
                return ResourceManager.GetString("OtherCodeTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherConfig_0001&quot;: &quot;音樂&quot;,
        ///      &quot;OtherConfig_0002&quot;: &quot;音效&quot;,
        ///      &quot;OtherConfig_0003&quot;: &quot;語音&quot;,
        ///      &quot;OtherConfig_0004&quot;: &quot;回合結束確認&quot;,
        ///      &quot;OtherConfig_0005&quot;: &quot;顯示敵方表情&quot;,
        ///      &quot;OtherConfig_0006&quot;: &quot;開&quot;,
        ///      &quot;OtherConfig_0007&quot;: &quot;關&quot;,
        ///      &quot;OtherConfig_0008&quot;: &quot;開&quot;,
        ///      &quot;OtherConfig_0009&quot;: &quot;關&quot;,
        ///      &quot;OtherConfig_0010&quot;: &quot;簡化戰鬥特效&quot;,
        ///      &quot;OtherConfig_0011&quot;: &quot;固定螢幕方向&quot;,
        ///      &quot;OtherConfig_0012&quot;: &quot;開&quot;,
        ///      &quot;OtherConfig_0013&quot;: &quot;關&quot;,
        ///      &quot;OtherConfig_0014&quot;: &quot;自動播放劇情&quot;,
        ///      &quot;OtherConfig_0015&quot;: &quot;開&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherConfigTextJson {
            get {
                return ResourceManager.GetString("OtherConfigTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherFriend_0001&quot;: &quot;好友&quot;,
        ///      &quot;OtherFriend_0002&quot;: &quot;好友一覽&quot;,
        ///      &quot;OtherFriend_0003&quot;: &quot;申請中&quot;,
        ///      &quot;OtherFriend_0004&quot;: &quot;等待通過&quot;,
        ///      &quot;OtherFriend_0005&quot;: &quot;通過&quot;,
        ///      &quot;OtherFriend_0006&quot;: &quot;好友檢索&quot;,
        ///      &quot;OtherFriend_0007&quot;: &quot;上次登録時間&quot;,
        ///      &quot;OtherFriend_0008&quot;: &quot;{0}分鐘前&quot;,
        ///      &quot;OtherFriend_0009&quot;: &quot;{0}小時前&quot;,
        ///      &quot;OtherFriend_0010&quot;: &quot;{0}天前&quot;,
        ///      &quot;OtherFriend_0011&quot;: &quot;全部取消&quot;,
        ///      &quot;OtherFriend_0012&quot;: &quot;移除&quot;,
        ///      &quot;OtherFriend_0013&quot;: &quot;全部取消&quot;,
        ///      &quot;OtherFriend_0014&quot;: &quot;通過&quot;,
        ///      &quot;OtherFriend_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherFriendTextJson {
            get {
                return ResourceManager.GetString("OtherFriendTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherPassword_0006&quot;: &quot;輸入代碼&quot;,
        ///      &quot;OtherPassword_0007&quot;: &quot;確定以輸入的代碼來下載資料嘛？&quot;,
        ///      &quot;OtherPassword_0001&quot;: &quot;通過發行代碼可以在別的終端進行遊玩。&quot;,
        ///      &quot;OtherPassword_0002&quot;: &quot;此外，資料發生破損的時候可以使用代碼來使資料恢復。&quot;,
        ///      &quot;OtherPassword_0003&quot;: &quot;按下下面的按鈕，可以在此處發行代碼。&quot;,
        ///      &quot;OtherPassword_0004&quot;: &quot;注意：現在遊戲中的存档資料會被現在輸入的資料所覆蓋。&quot;,
        ///      &quot;OtherPassword_0005&quot;: &quot;建議祢在輸入代碼之前先保存好現在存档資料的代碼。&quot;,
        ///      &quot;OtherPassword_0008&quot;: &quot;發行&quot;
        ///}.
        /// </summary>
        internal static string OtherPasswordTextJson {
            get {
                return ResourceManager.GetString("OtherPasswordTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Profile_0001&quot;: &quot;戰績&quot;,
        ///      &quot;Profile_0002&quot;: &quot;昵稱&quot;,
        ///      &quot;Profile_0003&quot;: &quot;稱號&quot;,
        ///      &quot;Profile_0004&quot;: &quot;變更徽章&quot;,
        ///      &quot;Profile_0005&quot;: &quot;變更旗幟&quot;,
        ///      &quot;Profile_0006&quot;: &quot;變更稱號&quot;,
        ///      &quot;Profile_0007&quot;: &quot;變更昵稱&quot;,
        ///      &quot;Profile_0008&quot;: &quot;玩家ID&quot;,
        ///      &quot;Profile_0009&quot;: &quot;複製&quot;,
        ///      &quot;Profile_0010&quot;: &quot;對戰積分&quot;,
        ///      &quot;Profile_0011&quot;: &quot;NEXT&quot;,
        ///      &quot;Profile_0012&quot;: &quot;等級一覽&quot;,
        ///      &quot;Profile_0013&quot;: &quot;職業角色勝利次數&quot;,
        ///      &quot;Profile_0014&quot;: &quot;玩家名已變更為\n{0}&quot;,
        ///      &quot;Profile_0015&quot;: &quot;已複製玩家ID&quot;,
        ///      &quot;Profile_0016&quot;: &quot;Page&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherProfileTextJson {
            get {
                return ResourceManager.GetString("OtherProfileTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Ranking_0001_Menu&quot;: &quot;對戰積分&quot;,
        ///      &quot;Ranking_0001_Header&quot;: &quot;對戰積分排行榜&quot;,
        ///      &quot;Ranking_0002_Menu&quot;: &quot;大師級積分&quot;,
        ///      &quot;Ranking_0002_Header&quot;: &quot;大師級積分排行榜&quot;,
        ///      &quot;Ranking_0003_Menu&quot;: &quot;天梯勝場&quot;,
        ///      &quot;Ranking_0003_Header&quot;: &quot;天梯勝場排行榜&quot;,
        ///      &quot;Ranking_0004_Menu&quot;: &quot;競技場&quot;,
        ///      &quot;Ranking_0004_Header_Old&quot;: &quot;競技場勝場排行榜&quot;,
        ///      &quot;Ranking_0004_Header_New&quot;: &quot;競技場5戰全勝排行榜&quot;,
        ///      &quot;Ranking_0101&quot;: &quot;勝&quot;,
        ///      &quot;Ranking_0102&quot;: &quot;pt&quot;,
        ///      &quot;Ranking_0103&quot;: &quot;次&quot;,
        ///      &quot;Ranking_0201&quot;: &quot;※戰績需要一定時間才能更新至排行榜。&quot;,
        ///      &quot;Ranking_02 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherRankingTextJson {
            get {
                return ResourceManager.GetString("OtherRankingTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherShareMovie_0001&quot;: &quot;分享遊戲録像&quot;
        ///}
        ///.
        /// </summary>
        internal static string OtherShareMovieTextJson {
            get {
                return ResourceManager.GetString("OtherShareMovieTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherTop_0001&quot;: &quot;個人資訊&quot;,
        ///      &quot;OtherTop_0002&quot;: &quot;排行榜&quot;,
        ///      &quot;OtherTop_0003&quot;: &quot;設定&quot;,
        ///      &quot;OtherTop_0004&quot;: &quot;繼承&quot;,
        ///      &quot;OtherTop_0005&quot;: &quot;好友&quot;,
        ///      &quot;OtherTop_0006&quot;: &quot;協助&quot;,
        ///      &quot;OtherTop_0007&quot;: &quot;諮詢&quot;,
        ///      &quot;OtherTop_0009&quot;: &quot;隱私條款&quot;,
        ///      &quot;OtherTop_0009_Update&quot;: &quot;隱私條款(更新)&quot;,
        ///      &quot;OtherTop_0010&quot;: &quot;服務協議&quot;,
        ///      &quot;OtherTop_0010_Update&quot;: &quot;服務協議(更新)&quot;,
        ///      &quot;OtherTop_0012&quot;: &quot;視頻録像設定&quot;,
        ///      &quot;OtherTop_0014&quot;: &quot;其它&quot;,
        ///      &quot;OtherTop_0015&quot;: &quot;相關連結&quot;,
        ///      &quot;OtherTop_0017&quot;: &quot;下載數據&quot;,
        ///      &quot;OtherTop_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherTopTextJson {
            get {
                return ResourceManager.GetString("OtherTopTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Practice_Maintenance&quot;: &quot;※練習模式維護中&quot;,
        ///      &quot;Practice_1001&quot;: &quot;亞里莎 - 初級&quot;,
        ///      &quot;Practice_1002&quot;: &quot;亞里莎 - 中級&quot;,
        ///      &quot;Practice_1003&quot;: &quot;亞里莎 - 高級(1)&quot;,
        ///      &quot;Practice_1004&quot;: &quot;亞里莎 - 高級(2)&quot;,
        ///      &quot;Practice_1005&quot;: &quot;亞里莎 - 超級(1)&quot;,
        ///      &quot;Practice_1006&quot;: &quot;亞里莎 - 超級(2)&quot;,
        ///      &quot;Practice_2001&quot;: &quot;艾莉華 - 初級&quot;,
        ///      &quot;Practice_2002&quot;: &quot;艾莉華 - 中級&quot;,
        ///      &quot;Practice_2003&quot;: &quot;艾莉華 - 高級(1)&quot;,
        ///      &quot;Practice_2004&quot;: &quot;艾莉華 - 高級(2)&quot;,
        ///      &quot;Practice_2005&quot;: &quot;艾莉華 - 超級(1)&quot;,
        ///      &quot;Practice_2006&quot;: &quot;艾莉華 - 超級(2)&quot;,
        ///      &quot;Pra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string practicetextmaster {
            get {
                return ResourceManager.GetString("practicetextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;1&quot;: &quot;青銅&quot;,
        ///      &quot;2&quot;: &quot;白銀&quot;,
        ///      &quot;3&quot;: &quot;黄金&quot;,
        ///      &quot;4&quot;: &quot;傳説&quot;
        ///}.
        /// </summary>
        internal static string raritynametextmaster {
            get {
                return ResourceManager.GetString("raritynametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;rarity_1&quot;: &quot;青銅&quot;,
        ///      &quot;rarity_2&quot;: &quot;白銀&quot;,
        ///      &quot;rarity_3&quot;: &quot;黄金&quot;,
        ///      &quot;rarity_4&quot;: &quot;傳説&quot;
        ///}.
        /// </summary>
        internal static string raritytextjson {
            get {
                return ResourceManager.GetString("raritytextjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;RoomBattle_0001&quot;: &quot;私人對戰&quot;,
        ///      &quot;RoomBattle_0002&quot;: &quot;創建房間&quot;,
        ///      &quot;RoomBattle_0003&quot;: &quot;進入房間&quot;,
        ///      &quot;RoomBattle_0004&quot;: &quot;觀戰&quot;,
        ///      &quot;RoomBattle_0005&quot;: &quot;有新的邀請&quot;,
        ///      &quot;RoomBattle_0006&quot;: &quot;輸入房間ID&quot;,
        ///      &quot;RoomBattle_0007&quot;: &quot;觀戰模式未開啓&quot;,
        ///      &quot;RoomBattle_0008&quot;: &quot;邀請好友&quot;,
        ///      &quot;RoomBattle_0009&quot;: &quot;房間ID&quot;,
        ///      &quot;RoomBattle_0010&quot;: &quot;聊天&quot;,
        ///      &quot;RoomBattle_0011&quot;: &quot;選擇牌組&quot;,
        ///      &quot;RoomBattle_0012&quot;: &quot;未選擇牌組\n\n請選擇\n使用的牌組&quot;,
        ///      &quot;RoomBattle_0013&quot;: &quot;到關閉房間為止&quot;,
        ///      &quot;RoomBattle_0014&quot;: &quot;15秒内最多只能發送3條訊息&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoomBattleTextJson {
            get {
                return ResourceManager.GetString("RoomBattleTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Shop_0001&quot;: &quot;購買牌包&quot;,
        ///      &quot;Shop_0002&quot;: &quot;購買牌背&quot;,
        ///      &quot;Shop_0003&quot;: &quot;購買水晶&quot;,
        ///      &quot;Shop_0004&quot;: &quot;抽取率&quot;,
        ///      &quot;Shop_0005&quot;: &quot;交易通知&quot;,
        ///      &quot;Shop_0006&quot;: &quot;牌包{0}&quot;,
        ///      &quot;Shop_0007&quot;: &quot;牌包資訊取得失敗。&quot;,
        ///      &quot;Shop_0028&quot;: &quot;牌包兌換券&quot;,
        ///      &quot;Shop_0010&quot;: &quot;獲得牌&quot;,
        ///      &quot;Shop_0009&quot;: &quot;祢今日不能開更多的牌包了。&quot;,
        ///      &quot;Shop_0011&quot;: &quot;取得牌背資訊失敗。&quot;,
        ///      &quot;Shop_0012&quot;: &quot;點撃選擇牌背。&quot;,
        ///      &quot;Shop_0014&quot;: &quot;已購買「{0}」牌背。&quot;,
        ///      &quot;Shop_0013&quot;: &quot;水晶不足。\n進入水晶購買畫面嘛？&quot;,
        ///      &quot;Shop_0015&quot;: &quot;點撃後打開&quot;,
        ///      &quot;Shop_0016&quot;: &quot;下一歩&quot;,
        ///      &quot;Shop_0025&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShopTextJson {
            get {
                return ResourceManager.GetString("ShopTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;SD_100011010_01&quot;: &quot;&quot;,
        ///      &quot;SD_100011010_02&quot;: &quot;&quot;,
        ///      &quot;SD_100011020_01&quot;: &quot;&quot;,
        ///      &quot;SD_100011020_02&quot;: &quot;&quot;,
        ///      &quot;SD_100011030_01&quot;: &quot;&quot;,
        ///      &quot;SD_100011030_02&quot;: &quot;&quot;,
        ///      &quot;SD_100011040_01&quot;: &quot;&quot;,
        ///      &quot;SD_100011040_02&quot;: &quot;&quot;,
        ///      &quot;SD_100011050_01&quot;: &quot;[u][ffcd45]守護[-][/u]&quot;,
        ///      &quot;SD_100011050_02&quot;: &quot;[u][ffcd45]守護[-][/u]&quot;,
        ///      &quot;SD_100012010&quot;: &quot;己方回合開始時，使1個隨機的己方隨從獲得+1/+1。&quot;,
        ///      &quot;SD_100031010_01&quot;: &quot;[u][ffcd45]攻撃時[-][/u] 對敵方英雄造成2點傷害。\n己方回合開始時，和己方場上的1個[u][ffcd45]囚罪雙子・琉璃[-][/u]融合為[u][ffcd45 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string skilldesctextmaster {
            get {
                return ResourceManager.GetString("skilldesctextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;SN_スタンダード1&quot;: &quot;標準&quot;,
        ///      &quot;SN_スタンダード2&quot;: &quot;精靈&quot;,
        ///      &quot;SN_スタンダード3&quot;: &quot;皇室護衛&quot;,
        ///      &quot;SN_スタンダード4&quot;: &quot;巫師&quot;,
        ///      &quot;SN_スタンダード5&quot;: &quot;竜&quot;,
        ///      &quot;SN_スタンダード6&quot;: &quot;死靈術士&quot;,
        ///      &quot;SN_スタンダード7&quot;: &quot;吸血鬼&quot;,
        ///      &quot;SN_スタンダード8&quot;: &quot;主教&quot;,
        ///      &quot;SN_アリサスリーブ&quot;: &quot;亞里莎&quot;,
        ///      &quot;SN_エリカスリーブ&quot;: &quot;艾莉華&quot;,
        ///      &quot;SN_イザベルスリーブ&quot;: &quot;伊莎貝爾&quot;,
        ///      &quot;SN_ローウェンスリーブ&quot;: &quot;羅文&quot;,
        ///      &quot;SN_ルナスリーブ&quot;: &quot;露娜&quot;,
        ///      &quot;SN_ユリアススリーブ&quot;: &quot;尤里亞斯&quot;,
        ///      &quot;SN_イリススリーブ&quot;: &quot;伊莉絲&quot;,
        ///      &quot;SN_神撃のバハムート1&quot;: &quot;巴哈姆特之怒(1)&quot;,
        ///      &quot;SN_神撃のバハムート2&quot;: &quot;巴哈姆特之怒(2)&quot;,
        ///      &quot;SN_神撃のバハムート [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sleevenametextmaster {
            get {
                return ResourceManager.GetString("sleevenametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;sleeve_1&quot;: &quot;巴哈姆特之怒(1-2)&quot;,
        ///      &quot;sleeve_2&quot;: &quot;巴哈姆特之怒(3-5)&quot;,
        ///      &quot;sleeve_3&quot;: &quot;牌背(3)&quot;,
        ///      &quot;sleeve_4&quot;: &quot;牌背(4)&quot;,
        ///      &quot;sleeve_5&quot;: &quot;牌背(5)&quot;,
        ///      &quot;sleeve_6&quot;: &quot;牌背(6)&quot;,
        ///      &quot;sleeve_7&quot;: &quot;碧藍幻想(1-3)&quot;,
        ///      &quot;sleeve_8&quot;: &quot;碧藍幻想(4-6)&quot;,
        ///      &quot;sleeve_9&quot;: &quot;偶像大師(1-3)&quot;,
        ///      &quot;sleeve_10&quot;: &quot;偶像大師(4-6)&quot;,
        ///      &quot;sleeve_11&quot;: &quot;聖鈴天使&quot;,
        ///      &quot;sleeve_12&quot;: &quot;命運之末・烏露德&quot;,
        ///      &quot;sleeve_13&quot;: &quot;雪人&quot;,
        ///      &quot;sleeve_14&quot;: &quot;乙姫護衛隊&quot;,
        ///      &quot;sleeve_15&quot;: &quot;艾拉的祈禱&quot;,
        ///      &quot;sleeve_16&quot;: &quot;精靈少女・莉薩&quot;
        ///}.
        /// </summary>
        internal static string sleeveproducttextmaster {
            get {
                return ResourceManager.GetString("sleeveproducttextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;SSN_ファーストシリーズ&quot;: &quot;第一彈&quot;,
        ///      &quot;SSN_セカンドシリーズ&quot;: &quot;第二彈&quot;
        ///}.
        /// </summary>
        internal static string sleeveseriesnametextmaster {
            get {
                return ResourceManager.GetString("sleeveseriesnametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;SSN_ファーストシリーズ&quot;: &quot;第一彈&quot;,
        ///      &quot;SSN_セカンドシリーズ&quot;: &quot;第二彈&quot;,
        ///      &quot;SSN_サードシリーズ&quot;: &quot;第三彈&quot;,
        ///      &quot;SSN_フォースシリーズ&quot;: &quot;第四彈&quot;,
        ///      &quot;SSI_神撃のバハムート&quot;: &quot;收集牌，組成牌組，在秘銀大陸的世界進行冒險的\n集換式牌幻想類角色扮演遊戲！\n在編輯牌組中可以變更牌背。&quot;,
        ///      &quot;SSI_セカンドシリーズ&quot;: &quot;第二彈介紹&quot;,
        ///      &quot;SSI_サードシリーズ&quot;: &quot;第三彈介紹&quot;,
        ///      &quot;SSI_グランブルーファンタジー&quot;: &quot;在蔚藍的天空冒險的正統角色扮演遊戲！\n戰鬥中可以使用能造成巨大傷害的「奧義」\n或強力的「星晶獸」，簡單的操作就能\n體驗華麗的戰鬥！\n在編輯牌組中可以變更牌背。&quot;,
        ///      &quot;SSI_アイドルマスターシンデレラガールズ&quot;: &quot;即刻領取偶像大師的聯動牌背！\n祢還在猶豫什麼？\n馬上擁有它！\n在編輯牌組中可以變更牌背。&quot;,
        ///      &quot;SSI_累積BP報酬&quot;: &quot;2016年10月～12月的累積BP獎勵！\n除牌背之外還 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sleeveseriestextmaster {
            get {
                return ResourceManager.GetString("sleeveseriestextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Story_0001&quot;: &quot;選擇英雄&quot;,
        ///      &quot;Story_0002&quot;: &quot;選擇章節&quot;,
        ///      &quot;Story_0013&quot;: &quot;章節 {0}&quot;,
        ///      &quot;Story_0003&quot;: &quot;開始章節 {0}&quot;,
        ///      &quot;Story_0004&quot;: &quot;繼續&quot;,
        ///      &quot;Story_0005&quot;: &quot;※請點撃&quot;,
        ///      &quot;Story_0006&quot;: &quot;詳細&quot;,
        ///      &quot;Story_0011&quot;: &quot;普通&quot;,
        ///      &quot;Story_0012&quot;: &quot;困難&quot;,
        ///      &quot;Story_0024&quot;: &quot;初級&quot;,
        ///      &quot;Story_0025&quot;: &quot;中級&quot;,
        ///      &quot;Story_0026&quot;: &quot;高級(1)&quot;,
        ///      &quot;Story_0034&quot;: &quot;高級(2)&quot;,
        ///      &quot;Story_0033&quot;: &quot;超級&quot;,
        ///      &quot;Story_0014&quot;: &quot;状態：完成&quot;,
        ///      &quot;Story_0015&quot;: &quot;新章節已開放&quot;,
        ///      &quot;Story_0016&quot;: &quot;選擇對戰對手&quot;,
        ///      &quot;Story_0017 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoryTextJson {
            get {
                return ResourceManager.GetString("StoryTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;ST_chapter_01_01&quot;: &quot;第1章 啓程&quot;,
        ///      &quot;ST_chapter_01_02&quot;: &quot;第2章 幽闇森林&quot;,
        ///      &quot;ST_chapter_01_03&quot;: &quot;第3章 通靈少女&quot;,
        ///      &quot;ST_chapter_01_04&quot;: &quot;第4章 黑竜&quot;,
        ///      &quot;ST_chapter_01_05&quot;: &quot;第5章 重要的人&quot;,
        ///      &quot;ST_chapter_01_06&quot;: &quot;第6章 心靈的黑闇&quot;,
        ///      &quot;ST_chapter_01_07&quot;: &quot;第7章 回憶&quot;,
        ///      &quot;ST_chapter_01_08&quot;: &quot;第8章 災厄之樹&quot;,
        ///      &quot;ST_chapter_02_01&quot;: &quot;第1章 王命&quot;,
        ///      &quot;ST_chapter_02_02&quot;: &quot;第2章 邂逅&quot;,
        ///      &quot;ST_chapter_02_03&quot;: &quot;第3章 共振&quot;,
        ///      &quot;ST_chapter_02_04&quot;: &quot;第4章 憂鬱的騎士&quot;,
        ///      &quot;ST_chapter_02_05&quot;: &quot;第5章 代價&quot;,
        ///      &quot;ST_chap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string storytextmaster {
            get {
                return ResourceManager.GetString("storytextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;System_TimeDateLong&quot;: &quot;yyyy/MM/dd HH:mm&quot;,
        ///      &quot;System_TimeDateShort&quot;: &quot;MM/dd HH:mm&quot;,
        ///      &quot;System_DateLong&quot;: &quot;yyyy/MM/dd&quot;,
        ///      &quot;System_DateShort&quot;: &quot;MM/dd&quot;,
        ///      &quot;System_Time&quot;: &quot;HH:mm&quot;,
        ///      &quot;System_YearMonth&quot;: &quot;yyyy/MM&quot;,
        ///      &quot;System_Between&quot;: &quot;{0} ～ {1}&quot;,
        ///      &quot;System_LineHeadWrap&quot;: &quot;､、｡。)）］」』}｝】,〕〉＞》≫〟’”.・:; 　!?！？…ー～－☆★♪，‐＝゛゜％/&quot;,
        ///      &quot;System_LineEndWrap&quot;: &quot;(（［{｛〔〈＜《≪「『【〝‘“×+＋/-&quot;,
        ///      &quot;System_0001&quot;: &quot;載入中&quot;,
        ///      &quot;System_0002&quot;: &quot;代碼&quot;,
        ///      &quot;System_0003&quot;: &quot;網路連接出錯&quot;,
        ///      &quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemTextJson {
            get {
                return ResourceManager.GetString("SystemTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Title_0002&quot;: &quot;請輸入昵稱&quot;,
        ///      &quot;Title_0001&quot;: &quot;註冊昵稱&quot;,
        ///      &quot;Title_0003&quot;: &quot;昵稱註冊完成&quot;,
        ///      &quot;Title_0004&quot;: &quot;昵稱:{0}\n註冊完成&quot;,
        ///      &quot;Title_0005&quot;: &quot;昵稱:{0}\n註冊失敗。\n請重新註冊昵稱。&quot;,
        ///      &quot;Title_0006&quot;: &quot;選單&quot;,
        ///      &quot;Title_0007&quot;: &quot;清除緩存&quot;,
        ///      &quot;Title_0008&quot;: &quot;清除緩存的話可能可以減輕硬體的負擔。\n不會刪除遊戲的存档資料。\n清除緩存後會再次下載相關資料。\n根據網路連接状況，可能會花費較長時間。\n\n確定清除緩存嘛？\n[ffcd45]清除緩存會導致正在進行中的對局結算為敗北。[-]&quot;,
        ///      &quot;Title_0009&quot;: &quot;緩存已清除。&quot;,
        ///      &quot;Title_0010&quot;: &quot;下載數據&quot;,
        ///      &quot;Title_0011&quot;: &quot;檢測到有新的資料。\n請點撃確認鍵進行下載。&quot;,
        ///      &quot;Title_0012&quot;: &quot;資料下載完成&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TitleTextJson {
            get {
                return ResourceManager.GetString("TitleTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;TN_ALL&quot;: &quot;ALL&quot;,
        ///      &quot;TN_兵士&quot;: &quot;士兵&quot;,
        ///      &quot;TN_指揮官&quot;: &quot;指揮官&quot;,
        ///      &quot;TN_土の印&quot;: &quot;土之印&quot;
        ///}.
        /// </summary>
        internal static string tribenametextmaster {
            get {
                return ResourceManager.GetString("tribenametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Tutorial_0001&quot;: &quot;蘿沙麗亞真厲害！&quot;,
        ///      &quot;Tutorial_0002&quot;: &quot;真開心哇！&quot;,
        ///      &quot;Tutorial_0003&quot;: &quot;教程資訊(3)&quot;,
        ///      &quot;Tutorial_0004&quot;: &quot;章節{0}&quot;,
        ///      &quot;Tutorial_0005&quot;: &quot;亞里莎&quot;,
        ///      &quot;Tutorial_0006&quot;: &quot;章節{0}&quot;,
        ///      &quot;Tutorial_0007&quot;: &quot;教程&quot;,
        ///      &quot;Tutorial_0008&quot;: &quot;跳過教程&quot;,
        ///      &quot;Tutorial_0009&quot;: &quot;跳過本場戰鬥嘛？&quot;,
        ///      &quot;Tutorial_0010&quot;: &quot;請先選擇單人遊戲&quot;
        ///}.
        /// </summary>
        internal static string TutorialTextJson {
            get {
                return ResourceManager.GetString("TutorialTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;TT_Title0001&quot;: &quot;使用牌&quot;,
        ///      &quot;TT_Title0002&quot;: &quot;教程&quot;,
        ///      &quot;TT_Title0003&quot;: &quot;攻撃&quot;,
        ///      &quot;TT_Title0004&quot;: &quot;守護&quot;,
        ///      &quot;TT_Title0005&quot;: &quot;進化(1)&quot;,
        ///      &quot;TT_Title0006&quot;: &quot;進化(2)&quot;,
        ///      &quot;TT_Title0007&quot;: &quot;結界牌(1)&quot;,
        ///      &quot;TT_Title0008&quot;: &quot;結界牌(2)&quot;,
        ///      &quot;TT_Title0009&quot;: &quot;咒術牌(1)&quot;,
        ///      &quot;TT_Title0010&quot;: &quot;咒術牌(2)&quot;,
        ///      &quot;TT_Title0011&quot;: &quot;交換手牌&quot;,
        ///      &quot;TT_Title0012&quot;: &quot;實戰&quot;,
        ///      &quot;TT_Title0013&quot;: &quot;教程完成&quot;,
        ///      &quot;TT_Desc0001&quot;: &quot;消費與牌的消耗相應的PP(法力値)，可以召喚(使用)手牌。\n\n向前拉動手牌中的「地精戰士」來召喚(使用)它。&quot;,
        ///      &quot;TT_Desc0002&quot;: &quot;召 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tutorialtextmaster {
            get {
                return ResourceManager.GetString("tutorialtextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;URL_0001&quot;: &quot;https://shadowverse.jp/faq/?fromapp&quot;,
        ///      &quot;URL_0002&quot;: &quot;http://sennatsu.com/&quot;,
        ///      &quot;URL_0003&quot;: &quot;https://shadowverse.jp/&quot;,
        ///      &quot;URL_0012&quot;: &quot;https://shadowverse.jp/gameguide/&quot;,
        ///      &quot;URL_0004_dmm&quot;: &quot;https://dmm.shadowverse.jp/news/&quot;,
        ///      &quot;URL_0005_dmm&quot;: &quot;https://dmm.shadowverse.jp/about/&quot;,
        ///      &quot;URL_0006_dmm&quot;: &quot;https://dmm.shadowverse.jp/copyright/&quot;,
        ///      &quot;URL_0007_dmm&quot;: &quot;https://dmm.shadowverse.jp/privacy/&quot;,
        ///      &quot;URL_0008_dmm&quot;: &quot;https://dmm.shadowverse.jp/fund/&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string URLTextJson {
            get {
                return ResourceManager.GetString("URLTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;VideoHosting_0001&quot;: &quot;録影/直播/觀看&quot;,
        ///      &quot;VideoHosting_0002&quot;: &quot;録影設定&quot;,
        ///      &quot;VideoHosting_0003&quot;: &quot;NICO直播設定&quot;,
        ///      &quot;VideoHosting_0004&quot;: &quot;發布至NICO視頻&quot;,
        ///      &quot;VideoHosting_0005&quot;: &quot;觀看NICO視頻&quot;,
        ///      &quot;VideoHosting_0006&quot;: &quot;録影模式&quot;,
        ///      &quot;VideoHosting_0007&quot;: &quot;NICO直播/觀看&quot;,
        ///      &quot;VideoHosting_0008&quot;: &quot;録影/觀看&quot;,
        ///      &quot;VideoHosting_0009&quot;: &quot;直播模式&quot;,
        ///      &quot;VideoHosting_0010&quot;: &quot;開&quot;,
        ///      &quot;VideoHosting_0011&quot;: &quot;關&quot;,
        ///      &quot;VideoHosting_0012&quot;: &quot;NICO視頻録影&quot;,
        ///      &quot;VideoHosting_0013&quot;: &quot;顯示對戰者的玩家昵稱&quot;,
        ///      &quot;VideoHo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VideoHostingTextJson {
            get {
                return ResourceManager.GetString("VideoHostingTextJson", resourceCulture);
            }
        }
    }
}
