//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galstars.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galstars.Extensions.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Account_0001&quot;: &quot;存档继承&quot;,
        ///      &quot;Account_0002&quot;: &quot;请输入继承代码&quot;,
        ///      &quot;Account_0003&quot;: &quot;※请确认输入内容是否正确&quot;,
        ///      &quot;Account_0004&quot;: &quot;请选择继承方法&quot;,
        ///      &quot;Account_0005&quot;: &quot;请在之前使用的设备发行继承代码，\n以进行游戏存档数据的继承。&quot;,
        ///      &quot;Account_0006&quot;: &quot;请选择外部链接进行认证，\n以继承关联的游戏存档数据。&quot;,
        ///      &quot;Account_0007&quot;: &quot;输入继承代码&quot;,
        ///      &quot;Account_0008&quot;: &quot;请输入发送到您登录的邮箱的继承代码。&quot;,
        ///      &quot;Account_0009&quot;: &quot;根据您所输入的继承代码，没有找到相关游戏存档数据。\n\n非常抱歉，请您确认代码是否正确之后再次尝试。&quot;,
        ///      &quot;Account_0010&quot;: &quot;您输入的继承代码超过了有效期限。\n非常抱歉，请从[ffcd45]现在游玩Shadowverse的设备[-]\n再次发行继承代码。&quot;,
        ///      &quot;Acco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountTextJson {
            get {
                return ResourceManager.GetString("AccountTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Arena_0001&quot;: &quot;竞技场&quot;,
        ///      &quot;Arena_0002&quot;: &quot;双选模式&quot;,
        ///      &quot;Arena_0003&quot;: &quot;关于双选模式&quot;,
        ///      &quot;Arena_0015&quot;: &quot;期间&quot;,
        ///      &quot;Arena_0004&quot;: &quot;使用入场券&quot;,
        ///      &quot;Arena_0005&quot;: &quot;设定参加费用&quot;,
        ///      &quot;Arena_0006&quot;: &quot;将使用金币\n或竞技场入场券\n来作为参加费用&quot;,
        ///      &quot;Arena_0007&quot;: &quot;请选择一个职业&quot;,
        ///      &quot;Arena_0008&quot;: &quot;选择卡牌&quot;,
        ///      &quot;Arena_0009&quot;: &quot;确认牌组&quot;,
        ///      &quot;Arena_0010&quot;: &quot;牌组张数\n{0}/{1}&quot;,
        ///      &quot;Arena_0011&quot;: &quot;&quot;,
        ///      &quot;Arena_0012&quot;: &quot;还有{0}次&quot;,
        ///      &quot;Arena_0014&quot;: &quot;结束双选模式获得奖励&quot;,
        ///      &quot;Arena_0016&quot;: &quot;对战\n开始&quot;,
        ///      &quot;Arena_0017&quot;: &quot;现在获得的奖励&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArenaTextJson {
            get {
                return ResourceManager.GetString("ArenaTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Arena_Load_0001&quot;: &quot;双选模式&quot;,
        ///      &quot;Arena_Load_0002&quot;: &quot;通过选择15组卡牌来组成合计30张牌的卡组，\n并连续进行5场比赛来赢得您的报酬。&quot;,
        ///      &quot;Arena_Load_0003&quot;: &quot;选择参赛方式&quot;
        ///}.
        /// </summary>
        internal static string arenatextmaster {
            get {
                return ResourceManager.GetString("arenatextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Battle_keyword_Title_0001&quot;: &quot;启言&quot;,
        ///      &quot;Battle_keyword_Title_0002&quot;: &quot;终语&quot;,
        ///      &quot;Battle_keyword_Title_0003&quot;: &quot;进化时&quot;,
        ///      &quot;Battle_keyword_Title_0004&quot;: &quot;攻击时&quot;,
        ///      &quot;Battle_keyword_Title_0005&quot;: &quot;守护&quot;,
        ///      &quot;Battle_keyword_Title_0006&quot;: &quot;疾走&quot;,
        ///      &quot;Battle_keyword_Title_0007&quot;: &quot;潜伏&quot;,
        ///      &quot;Battle_keyword_Title_0008&quot;: &quot;必杀&quot;,
        ///      &quot;Battle_keyword_Title_0009&quot;: &quot;系命&quot;,
        ///      &quot;Battle_keyword_Title_0010&quot;: &quot;觉醒&quot;,
        ///      &quot;Battle_keyword_Title_0011&quot;: &quot;复仇&quot;,
        ///      &quot;Battle_keyword_Title_0012&quot;: &quot;共鸣&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string battlekeywordmaster {
            get {
                return ResourceManager.GetString("battlekeywordmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Battle_0004&quot;: &quot;双选模式&quot;,
        ///      &quot;Battle_0001&quot;: &quot;自由匹配&quot;,
        ///      &quot;Battle_0002&quot;: &quot;天梯匹配&quot;,
        ///      &quot;Battle_0003&quot;: &quot;私人对战&quot;,
        ///      &quot;Battle_0005&quot;: &quot;选择牌组(自由匹配)&quot;,
        ///      &quot;Battle_0006&quot;: &quot;选择牌组(天梯匹配)&quot;,
        ///      &quot;Battle_0007&quot;: &quot;选择牌组(私人对战)&quot;,
        ///      &quot;Battle_0008&quot;: &quot;匹配中&quot;,
        ///      &quot;Battle_0300&quot;: &quot;重新连接吗？&quot;,
        ///      &quot;Battle_0301&quot;: &quot;重试&quot;,
        ///      &quot;Battle_0014&quot;: &quot;房间 ID {0}&quot;,
        ///      &quot;Battle_0013&quot;: &quot;进入房间&quot;,
        ///      &quot;Battle_0302&quot;: &quot;进入房间出错&quot;,
        ///      &quot;Battle_0009&quot;: &quot;晋级战&quot;,
        ///      &quot;Battle_0010&quot;: &quot;本次对战胜利即可晋级&quot;,
        ///      &quot;Battle_0164&quot;: &quot;胜利！&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BattleTextJson {
            get {
                return ResourceManager.GetString("BattleTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;BT_100011010&quot;: &quot;&quot;,
        ///      &quot;BT_100011020&quot;: &quot;&quot;,
        ///      &quot;BT_100011030&quot;: &quot;&quot;,
        ///      &quot;BT_100011040&quot;: &quot;&quot;,
        ///      &quot;BT_100011050&quot;: &quot;&quot;,
        ///      &quot;BT_100012010&quot;: &quot;+1/+1&quot;,
        ///      &quot;BT_100031010&quot;: &quot;&quot;,
        ///      &quot;BT_100031020&quot;: &quot;&quot;,
        ///      &quot;BT_100111010&quot;: &quot;&quot;,
        ///      &quot;BT_100111020&quot;: &quot;&quot;,
        ///      &quot;BT_100111030&quot;: &quot;+1/+0&quot;,
        ///      &quot;BT_100111040&quot;: &quot;+1/+1，[ffcd45]守护[-]&quot;,
        ///      &quot;BT_100111050&quot;: &quot;+2/+2&quot;,
        ///      &quot;BT_100111060&quot;: &quot;&quot;,
        ///      &quot;BT_100111070&quot;: &quot;&quot;,
        ///      &quot;BT_100114010&quot;: &quot;&quot;,
        ///      &quot;BT_100121010&quot;: &quot;+1/+1&quot;,
        ///      &quot;BT_1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bufftextmaster {
            get {
                return ResourceManager.GetString("bufftextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;BDPN_構築済みデッキ1弾_エルフ&quot;: &quot;白银射手(精灵)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ロイヤル&quot;: &quot;盛宴开场(皇室护卫)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ウィッチ&quot;: &quot;法神降临(巫师)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ドラゴン&quot;: &quot;暗黑龙骑(龙)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ネクロマンサー&quot;: &quot;冥炎咆哮(死灵术士)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ヴァンパイア&quot;: &quot;女王之吻(血族)&quot;,
        ///      &quot;BDPN_構築済みデッキ1弾_ビショップ&quot;: &quot;圣洁战场(主教)&quot;,
        ///      &quot;BDPN_構築済みデッキ2弾_エルフ&quot;: &quot;异形之棘(精灵)&quot;,
        ///      &quot;BDPN_構築済みデッキ2弾_ロイヤル&quot;: &quot;疾风迅雷(皇室护卫)&quot;,
        ///      &quot;BDPN_構築済みデッキ2弾_ウィッチ&quot;: &quot;暴威魔能(巫师)&quot;,
        ///      &quot;BDPN_構築済みデッキ2弾_ドラゴン&quot;: &quot;水龙加护(龙)&quot;,
        ///      &quot;BDPN_構築済みデッキ2弾_ネクロマンサー&quot;: &quot;灵魂主宰(死 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string builddeckproducttextmaster {
            get {
                return ResourceManager.GetString("builddeckproducttextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;BDSSN_構築済みデッキ1弾&quot;: &quot;BDSSN_構築済みデッキ1弾&quot;,
        ///      &quot;BDSI_構築済みデッキ1弾&quot;: &quot;各套拥有1张限定版插画的豪华传说级卡牌（无法分解）。\n每套可购买3次，根据购买次数价格会产生变化。\n初次：水晶500个，之后：水晶750个。&quot;,
        ///      &quot;BDSSN_構築済みデッキ2弾&quot;: &quot;BDSSN_構築済みデッキ2弾&quot;,
        ///      &quot;BDSI_構築済みデッキ2弾&quot;: &quot;各套拥有1张限定版插画的豪华传说级卡牌（无法分解）。\n每套可购买3次，根据购买次数价格会产生变化。\n初次：水晶500个，之后：水晶750个。&quot;
        ///}.
        /// </summary>
        internal static string builddeckseriestextmaster {
            get {
                return ResourceManager.GetString("builddeckseriestextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;CN_100011010&quot;: &quot;地精战士&quot;,
        ///      &quot;CN_100011020&quot;: &quot;格斗士&quot;,
        ///      &quot;CN_101011010&quot;: &quot;牛头怪&quot;,
        ///      &quot;CN_101011020&quot;: &quot;沙漠骑手&quot;,
        ///      &quot;CN_100011030&quot;: &quot;流浪佣兵&quot;,
        ///      &quot;CN_100011040&quot;: &quot;巨兵卫&quot;,
        ///      &quot;CN_100011050&quot;: &quot;天剑神女&quot;,
        ///      &quot;CN_101011030&quot;: &quot;执盾天使&quot;,
        ///      &quot;CN_100031010&quot;: &quot;囚罪双子・烈焰&quot;,
        ///      &quot;CN_100031020&quot;: &quot;囚罪双子・琉璃&quot;,
        ///      &quot;CN_101021010&quot;: &quot;圣铃天使&quot;,
        ///      &quot;CN_101021020&quot;: &quot;蜥蜴怪人&quot;,
        ///      &quot;CN_101011040&quot;: &quot;愈光天使&quot;,
        ///      &quot;CN_101021030&quot;: &quot;英雄王・吉尔伽美什&quot;,
        ///      &quot;CN_101021040&quot;: &quot;地精恶魔骑手&quot;,
        ///      &quot;CN_101031010&quot;: &quot;命运之末・乌露德&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cardnametextmaster {
            get {
                return ResourceManager.GetString("cardnametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;90000_long&quot;: &quot;代币&quot;,
        ///      &quot;90000_short&quot;: &quot;TKN&quot;,
        ///      &quot;10000_long&quot;: &quot;基本&quot;,
        ///      &quot;10000_short&quot;: &quot;BSC&quot;,
        ///      &quot;10001_long&quot;: &quot;标准&quot;,
        ///      &quot;10001_short&quot;: &quot;STD&quot;,
        ///      &quot;10002_long&quot;: &quot;黑暗进化&quot;,
        ///      &quot;10002_short&quot;: &quot;DRK&quot;,
        ///      &quot;10003_long&quot;: &quot;巴哈姆特降临&quot;,
        ///      &quot;10003_short&quot;: &quot;ROB&quot;,
        ///      &quot;10004_long&quot;: &quot;诸神狂岚&quot;,
        ///      &quot;10004_short&quot;: &quot;TOG&quot;,
        ///      &quot;10005_long&quot;: &quot;梦境奇想&quot;,
        ///      &quot;10005_short&quot;: &quot;WLD&quot;
        ///}.
        /// </summary>
        internal static string cardsetnametextmaster {
            get {
                return ResourceManager.GetString("cardsetnametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Card_0001&quot;: &quot;牌组清单&quot;,
        ///      &quot;Card_0002&quot;: &quot;默认牌组&quot;,
        ///      &quot;Card_0004&quot;: &quot;默认&quot;,
        ///      &quot;Card_0005&quot;: &quot;牌柜&quot;,
        ///      &quot;Card_0006&quot;: &quot;使用[ffca45]{0}[-]&quot;,
        ///      &quot;Card_0007&quot;: &quot;编辑牌组&quot;,
        ///      &quot;Card_0042&quot;: &quot;编辑牌组&quot;,
        ///      &quot;Card_0008&quot;: &quot;删除牌组&quot;,
        ///      &quot;Card_0009&quot;: &quot;确定删除牌组吗？&quot;,
        ///      &quot;Card_0010&quot;: &quot;牌组已删除。&quot;,
        ///      &quot;Card_0011&quot;: &quot;牌组名&quot;,
        ///      &quot;Card_0012&quot;: &quot;请输入牌组名。&quot;,
        ///      &quot;Card_0014&quot;: &quot;名称已变更。&quot;,
        ///      &quot;Card_0018&quot;: &quot;保存&quot;,
        ///      &quot;Card_0019&quot;: &quot;牌组已保存。&quot;,
        ///      &quot;Card_0015&quot;: &quot;变更卡背&quot;,
        ///      &quot;Card_0016&quot;: &quot;把牌组{0}的卡背变更为{1}吗？&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CardTextJson {
            get {
                return ResourceManager.GetString("CardTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;CC_アリサ&quot;: &quot;亚里莎&quot;,
        ///      &quot;CC_エリカ&quot;: &quot;艾莉卡&quot;,
        ///      &quot;CC_イザベル&quot;: &quot;伊莎贝尔&quot;,
        ///      &quot;CC_ローウェン&quot;: &quot;罗文&quot;,
        ///      &quot;CC_ルナ&quot;: &quot;露娜&quot;,
        ///      &quot;CC_ユリアス&quot;: &quot;尤里亚斯&quot;,
        ///      &quot;CC_イリス&quot;: &quot;伊莉丝&quot;,
        ///      &quot;CC_ネクサス&quot;: &quot;涅墨西斯&quot;,
        ///      &quot;CC_ロザリア&quot;: &quot;萝沙丽亚&quot;,
        ///      &quot;CC_虚の影アリサ&quot;: &quot;虚之影 亚里莎&quot;,
        ///      &quot;CC_虚の影エリカ&quot;: &quot;虚之影 艾莉卡&quot;,
        ///      &quot;CC_虚の影イザベル&quot;: &quot;虚之影 伊莎贝尔&quot;,
        ///      &quot;CC_虚の影ローウェン&quot;: &quot;虚之影 罗文&quot;,
        ///      &quot;CC_虚の影ルナ&quot;: &quot;虚之影 露娜&quot;,
        ///      &quot;CC_虚の影ユリアス&quot;: &quot;虚之影 尤里亚斯&quot;,
        ///      &quot;CC_虚の影イリス&quot;: &quot;虚之影 伊莉丝&quot;,
        ///      &quot;CC_黒龍&quot;: &quot;黑龙&quot;,
        ///      &quot;CC_虚の影&quot;: &quot;虚之影&quot;,
        ///      &quot;CC_虚の影2&quot;: &quot;虚之 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string classcharanametextmaster {
            get {
                return ResourceManager.GetString("classcharanametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Common_0105&quot;: &quot;精灵&quot;,
        ///      &quot;Common_0106&quot;: &quot;皇室护卫&quot;,
        ///      &quot;Common_0107&quot;: &quot;巫师&quot;,
        ///      &quot;Common_0108&quot;: &quot;龙&quot;,
        ///      &quot;Common_0109&quot;: &quot;死灵术士&quot;,
        ///      &quot;Common_0110&quot;: &quot;血族&quot;,
        ///      &quot;Common_0111&quot;: &quot;主教&quot;
        ///}.
        /// </summary>
        internal static string classnametextmaster {
            get {
                return ResourceManager.GetString("classnametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;clan_0&quot;: &quot;中立&quot;,
        ///      &quot;clan_1&quot;: &quot;精灵&quot;,
        ///      &quot;clan_2&quot;: &quot;皇室护卫&quot;,
        ///      &quot;clan_3&quot;: &quot;巫师&quot;,
        ///      &quot;clan_4&quot;: &quot;龙&quot;,
        ///      &quot;clan_5&quot;: &quot;死灵术士&quot;,
        ///      &quot;clan_6&quot;: &quot;血族&quot;,
        ///      &quot;clan_7&quot;: &quot;主教&quot;
        ///}.
        /// </summary>
        internal static string classtextjson {
            get {
                return ResourceManager.GetString("classtextjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Common_0001&quot;: &quot;是&quot;,
        ///      &quot;Common_0002&quot;: &quot;否&quot;,
        ///      &quot;Common_0003&quot;: &quot;决定&quot;,
        ///      &quot;Common_0004&quot;: &quot;确认&quot;,
        ///      &quot;Common_0053&quot;: &quot;取消&quot;,
        ///      &quot;Common_0005&quot;: &quot;取消&quot;,
        ///      &quot;Common_0008&quot;: &quot;关闭&quot;,
        ///      &quot;Common_0009&quot;: &quot;点击&quot;,
        ///      &quot;Common_0021&quot;: &quot;信息&quot;,
        ///      &quot;Common_0022&quot;: &quot;详细&quot;,
        ///      &quot;Common_0026&quot;: &quot;输入&quot;,
        ///      &quot;Common_0036&quot;: &quot;情报&quot;,
        ///      &quot;Common_0042&quot;: &quot;下一级&quot;,
        ///      &quot;Common_0043&quot;: &quot;下一等级&quot;,
        ///      &quot;Common_0045&quot;: &quot;等级&quot;,
        ///      &quot;Common_0046&quot;: &quot;对战等级&quot;,
        ///      &quot;Common_0047&quot;: &quot;对战积分&quot;,
        ///      &quot;Common_0048&quot;: &quot;大师赛积分&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonTextJson {
            get {
                return ResourceManager.GetString("CommonTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Country_Category_Asia&quot;: &quot;亚洲&quot;,
        ///      &quot;Country_Category_Europe&quot;: &quot;欧洲&quot;,
        ///      &quot;Country_Category_Americas&quot;: &quot;北美及中南美&quot;,
        ///      &quot;Country_Category_Oceania&quot;: &quot;大洋洲&quot;,
        ///      &quot;Country_Category_Africa&quot;: &quot;非洲&quot;
        ///}.
        /// </summary>
        internal static string countrytextmaster {
            get {
                return ResourceManager.GetString("countrytextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;DEG_私だって戦えるんだから！&quot;: &quot;就算是我也会战斗！&quot;,
        ///      &quot;DEG_妖精少女&quot;: &quot;精灵少女&quot;,
        ///      &quot;DEG_約束の弓 誓いの矢&quot;: &quot;约定之弓 誓言之矢&quot;,
        ///      &quot;DEG_Elf Master&quot;: &quot;大师级精灵&quot;,
        ///      &quot;DEG_ここで死んで頂きます&quot;: &quot;请葬身于此吧&quot;,
        ///      &quot;DEG_メイドが本業&quot;: &quot;女仆是本职&quot;,
        ///      &quot;DEG_Save the Queen &quot;: &quot;拯救女皇&quot;,
        ///      &quot;DEG_Royal Master&quot;: &quot;大师级皇室护卫&quot;,
        ///      &quot;DEG_手加減なしよ、本気で行くわ！&quot;: &quot;我可不会手下留情！&quot;,
        ///      &quot;DEG_天才錬金術師&quot;: &quot;天才炼金术士&quot;,
        ///      &quot;DEG_禁忌の探求者&quot;: &quot;禁忌的探求者&quot;,
        ///      &quot;DEG_Witch Master&quot;: &quot;大师级巫师&quot;,
        ///      &quot;DEG_この俺が相手だ！&quot;: &quot;我来做你的对手！&quot;,
        ///      &quot;DEG_歴代最強竜騎士&quot;: &quot;历代最强龙骑士&quot;,
        ///      &quot;DEG_咎負いし黒龍騎士&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string degreetextmaster {
            get {
                return ResourceManager.GetString("degreetextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Dialog_Text_Alignment&quot;: &quot;Center&quot;,
        ///      &quot;Dia_Battle_001_Title&quot;: &quot;回合结束&quot;,
        ///      &quot;Dia_Battle_001_Button&quot;: &quot;结束&quot;,
        ///      &quot;Dia_Battle_002_Title&quot;: &quot;进化&quot;,
        ///      &quot;Dia_Battle_002_Button&quot;: &quot;进化&quot;,
        ///      &quot;Dia_Battle_003_Button&quot;: &quot;弃权&quot;,
        ///      &quot;Dia_Battle_003_Button_2&quot;: &quot;结束&quot;,
        ///      &quot;Dia_Result_001_Button&quot;: &quot;报告&quot;,
        ///      &quot;Dia_Tutorial_001_Button&quot;: &quot;跳过&quot;,
        ///      &quot;Dia_Title_001_Button&quot;: &quot;完成&quot;,
        ///      &quot;Dia_Title_002_Button&quot;: &quot;结束&quot;,
        ///      &quot;Dia_Web_001_Button&quot;: &quot;打开&quot;,
        ///      &quot;Dia_ChapterSelect_001_Button&quot;: &quot;开始&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DialogTextJson {
            get {
                return ResourceManager.GetString("DialogTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;EM_シャドウバース&quot;: &quot;暗影之诗&quot;,
        ///      &quot;EM_アリサ&quot;: &quot;亚里莎&quot;,
        ///      &quot;EM_エリカ&quot;: &quot;艾莉卡&quot;,
        ///      &quot;EM_イザベル&quot;: &quot;伊莎贝尔&quot;,
        ///      &quot;EM_ローウェン&quot;: &quot;罗文&quot;,
        ///      &quot;EM_ルナ&quot;: &quot;露娜&quot;,
        ///      &quot;EM_ユリアス&quot;: &quot;尤里亚斯&quot;,
        ///      &quot;EM_イリス&quot;: &quot;伊莉丝&quot;,
        ///      &quot;EM_セルウィン&quot;: &quot;箭神・塞尔温&quot;,
        ///      &quot;EM_レイサム&quot;: &quot;无畏先锋・莱瑟姆&quot;,
        ///      &quot;EM_エラスムス&quot;: &quot;大召唤师・伊拉斯谟&quot;,
        ///      &quot;EM_フォルテ&quot;: &quot;黑龙战骑・法露特&quot;,
        ///      &quot;EM_モルディカイ&quot;: &quot;决死者・莫迪凯&quot;,
        ///      &quot;EM_ヴァンピィ&quot;: &quot;吸血姬・斑比&quot;,
        ///      &quot;EM_ガルラ&quot;: &quot;天煌守护者・迦楼罗&quot;,
        ///      &quot;EM_ルシフェル&quot;: &quot;晨星天使・路西法&quot;,
        ///      &quot;EM_アテナ&quot;: &quot;知惠神・雅典娜&quot;,
        ///      &quot;EM_ファイター&quot;: &quot;格斗士&quot;,
        ///      &quot;EM_ローズ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emblemtextmaster {
            get {
                return ResourceManager.GetString("emblemtextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;ET_AI_01001_000_101&quot;: &quot;真不错啊！&quot;,
        ///      &quot;ET_AI_01001_000_102&quot;: &quot;这一招不错吧？&quot;,
        ///      &quot;ET_AI_01001_000_111&quot;: &quot;完蛋啦！&quot;,
        ///      &quot;ET_AI_01001_000_121&quot;: &quot;怎么会这样...&quot;,
        ///      &quot;ET_AI_01001_000_131&quot;: &quot;我放弃了～&quot;,
        ///      &quot;ET_AI_01001_000_141&quot;: &quot;来吧！&quot;,
        ///      &quot;ET_AI_01001_000_142&quot;: &quot;可别吓得逃跑哦！&quot;,
        ///      &quot;ET_AI_01001_000_151&quot;: &quot;哈啊???。&quot;,
        ///      &quot;ET_AI_01001_000_152&quot;: &quot;恩...&quot;,
        ///      &quot;ET_AI_01001_000_161&quot;: &quot;你还好吧？&quot;,
        ///      &quot;ET_AI_01001_000_162&quot;: &quot;确定要这样么？&quot;,
        ///      &quot;ET_AI_01001_000_191&quot;: &quot;打得漂亮！&quot;,
        ///      &quot;ET_AI_01001_000_192&quot;: &quot;哎哎!? [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emotetextmaster {
            get {
                return ResourceManager.GetString("emotetextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;ErrorHeader_DEFAULT&quot;: &quot;出错&quot;,
        ///      &quot;ErrorHeader_0001&quot;: &quot;出错&quot;,
        ///      &quot;ErrorHeader_0002&quot;: &quot;出错&quot;,
        ///      &quot;ErrorHeader_0003&quot;: &quot;出错&quot;,
        ///      &quot;ErrorHeader_0004&quot;: &quot;出错&quot;,
        ///      &quot;ErrorHeader_0005&quot;: &quot;系统维护中&quot;,
        ///      &quot;ErrorHeader_0006&quot;: &quot;超时&quot;,
        ///      &quot;ErrorHeader_0009&quot;: &quot;继承失败&quot;,
        ///      &quot;ErrorHeader_0010&quot;: &quot;继承失败&quot;,
        ///      &quot;ErrorHeader_0011&quot;: &quot;继承失败&quot;,
        ///      &quot;ErrorHeader_0012&quot;: &quot;网络连接出错&quot;,
        ///      &quot;ErrorHeader_0007&quot;: &quot;输入出错&quot;,
        ///      &quot;ErrorHeader_0008&quot;: &quot;输入出错&quot;,
        ///      &quot;ErrorHeader_0013&quot;: &quot;下载数据&quot;,
        ///      &quot;ErrorHeader_0014&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorHeaderTextJson {
            get {
                return ResourceManager.GetString("ErrorHeaderTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Error_DEFAULT&quot;: &quot;发生错误。\n如果问题无法解决，\n烦请附上错误代码进行咨询。\n(错误代码{0})&quot;,
        ///      &quot;Error_0001&quot;: &quot;错误&quot;,
        ///      &quot;Error_0002&quot;: &quot;错误&quot;,
        ///      &quot;Error_0003&quot;: &quot;出错了&quot;,
        ///      &quot;Error_0004&quot;: &quot;{0}出错了。&quot;,
        ///      &quot;Error_0005&quot;: &quot;系统维护中。\n\n在维护结束之前，请您耐心等待。&quot;,
        ///      &quot;Error_0006&quot;: &quot;超时了。&quot;,
        ///      &quot;Error_0009&quot;: &quot;继承失败了。\n(错误代码：9)&quot;,
        ///      &quot;Error_0010&quot;: &quot;继承的设定失败了。\n(错误代码：10)&quot;,
        ///      &quot;Error_0011&quot;: &quot;存档的继承失败了。\n(错误代码：11)&quot;,
        ///      &quot;Error_0012&quot;: &quot;网络连接发生错误。\n\n请确认网络连接状况后重试。\n&quot;,
        ///      &quot;Error_0007&quot;: &quot;超出字数限制或使用了禁止使用的字词。&quot;,
        ///      &quot;Error_0008&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ErrorTextJson {
            get {
                return ResourceManager.GetString("ErrorTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;FirstTips_0001&quot;: &quot;一套牌组由40张卡牌构成。\n在编辑牌组画面，\n向上拖动可以设定想使用的卡牌。\n移除时则向下拖动卡牌。&quot;,
        ///      &quot;FirstTips_0002&quot;: &quot;制作卡牌时需要红色以太。\n红色以太可以在游戏中通过报酬获取\n或分解卡牌来入手。&quot;,
        ///      &quot;FirstTips_0003&quot;: &quot;如果要制作1张自己没有的卡牌，\n可以选择「制作」来消耗红色以太来入手。\n(也有无法制作或分解的卡牌。)&quot;,
        ///      &quot;FirstTips_0004&quot;: &quot;双选模式是指反复从随机出现的备选卡牌中选取\n以组成随机的牌组来进行对战的模式。\n胜场越多，报酬越丰厚。&quot;,
        ///      &quot;FirstTips_0005&quot;: &quot;欢迎来到Shadowverse的世界。\n教程中获得的报酬可以随时在「礼物」中领取。&quot;,
        ///      &quot;FirstTips_0006&quot;: &quot;可以首先选择「单人」进行游戏。\n在单人模式中，与AI的对战获胜后，\n作为报酬，可获得各种各样的卡牌。&quot;,
        ///      &quot;FirstTips_0007&quot;: &quot;通过对战胜利，可以获得只能在剧情 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstTipsJson {
            get {
                return ResourceManager.GetString("FirstTipsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;FT_100011010_01&quot;: &quot;外表看起来稍微有点让人吃惊，但是其实没有什么了不起的。总之只是魔族的底层，即没有力量，也没有智慧。但是，还是要注意「狗急也会跳墙」。&quot;,
        ///      &quot;FT_100011010_02&quot;: &quot;稍微有点经验的人，就没必要害怕这种最低级的魔物。话虽如此，还是要注意武装了的它们。就算是穷酸可怜的小剑，被击中了还是会流血的。&quot;,
        ///      &quot;FT_100011020_01&quot;: &quot;如果说在这充满纷争的世界有能够依靠的东西，那就是自己的力量。所以我会一直胜利。一定会！&quot;,
        ///      &quot;FT_100011020_02&quot;: &quot;如果说在这充满纷争的世界有能够依靠的东西，那就是自己的力量。用这把剑开创的未来，就是我所追求的东西。&quot;,
        ///      &quot;FT_100011030_01&quot;: &quot;击退魔怪的委托？报酬当然会很多吧？如果得该得到的东西的话，会有超过期待的成果哦。&quot;,
        ///      &quot;FT_100011030_02&quot;: &quot;我会按照收到的报酬好好工作。绝对是一分钱，一份成果。这就是我的原则。那么，就开始工作吧……魔怪们！快来受死！你们的性命，就是我明天的食粮！&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string flavourtextmaster {
            get {
                return ResourceManager.GetString("flavourtextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;IT_1&quot;: &quot;竞技场入场券&quot;,
        ///      &quot;IT_1000&quot;: &quot;次元石&quot;,
        ///      &quot;IT_10001&quot;: &quot;标准卡包兑换券&quot;,
        ///      &quot;IT_10002&quot;: &quot;黑暗进化卡包兑换券&quot;,
        ///      &quot;IT_10003&quot;: &quot;巴哈姆特降临卡包兑换券&quot;,
        ///      &quot;IT_10004&quot;: &quot;诸神狂岚卡包兑换券&quot;,
        ///      &quot;IT_10005&quot;: &quot;梦境奇想卡包兑换券&quot;,
        ///      &quot;IT_10006&quot;: &quot;新卡包兑换券&quot;
        ///}.
        /// </summary>
        internal static string itemtextmaster {
            get {
                return ResourceManager.GetString("itemtextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;LSPPN_神撃のバハムート_1&quot;: &quot;箭神・塞尔温&quot;,
        ///      &quot;LSPPN_神撃のバハムート_2&quot;: &quot;无畏先锋・莱瑟姆&quot;,
        ///      &quot;LSPPN_神撃のバハムート_3&quot;: &quot;大召唤师・伊拉斯谟&quot;,
        ///      &quot;LSPPN_神撃のバハムート_4&quot;: &quot;黑龙战骑・法露特&quot;,
        ///      &quot;LSPPN_神撃のバハムート_5&quot;: &quot;决死者・莫迪凯&quot;,
        ///      &quot;LSPPN_神撃のバハムート_6&quot;: &quot;吸血姬・斑比&quot;,
        ///      &quot;LSPPN_神撃のバハムート_7&quot;: &quot;天煌守护者・迦楼罗&quot;,
        ///      &quot;LSPPN_SF5_1&quot;: &quot;嘉米怀特&quot;,
        ///      &quot;LSPPN_SF5_2&quot;: &quot;春丽&quot;,
        ///      &quot;LSPPN_SF5_3&quot;: &quot;韩蛛俐&quot;,
        ///      &quot;LSPPN_SF5_4&quot;: &quot;隆&quot;,
        ///      &quot;LSPPN_SF5_5&quot;: &quot;维加&quot;,
        ///      &quot;LSPPN_SF5_6&quot;: &quot;巴洛克&quot;,
        ///      &quot;LSPPN_SF5_7&quot;: &quot;神月卡琳&quot;,
        ///      &quot;LSPI_神撃のバハムート_1&quot;: &quot;他是身经百战的猎人，\n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leaderskinproducttextmaster {
            get {
                return ResourceManager.GetString("leaderskinproducttextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;LSSI_神撃のバハムート&quot;: &quot;巴哈姆特之怒皮肤。\n\n您可以在个人资料界面切换皮肤。&quot;,
        ///      &quot;LSSSN_神撃のバハムート&quot;: &quot;巴哈姆特之怒皮肤包&quot;,
        ///      &quot;LSSI_SF5&quot;: &quot;街头霸王5皮肤。\n\n您可以在个人资料界面切换皮肤。&quot;,
        ///      &quot;LSSSN_SF5&quot;: &quot;街头霸王5皮肤包&quot;
        ///}.
        /// </summary>
        internal static string leaderskinseriestextmaster {
            get {
                return ResourceManager.GetString("leaderskinseriestextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Load_0001&quot;: &quot;正在下载最新数据           &quot;,
        ///      &quot;Load_0002&quot;: &quot;请在网络状况良好的状态下进行下载。\n(根据网络连接状况，可能会花费较长时间)&quot;,
        ///      &quot;Load_0003&quot;: &quot;亚里莎&quot;,
        ///      &quot;Load_0004&quot;: &quot;艾莉卡&quot;,
        ///      &quot;Load_0005&quot;: &quot;伊莎贝尔&quot;,
        ///      &quot;Load_0006&quot;: &quot;罗文&quot;,
        ///      &quot;Load_0007&quot;: &quot;露娜&quot;,
        ///      &quot;Load_0008&quot;: &quot;尤里亚斯&quot;,
        ///      &quot;Load_0009&quot;: &quot;伊莉丝&quot;,
        ///      &quot;Load_0010&quot;: &quot;为了成为合格的森林守护者，\n每天都在努力修行的精灵少女。\n为了救回被不明身份的家伙\n掳走的好友而踏上了旅途。&quot;,
        ///      &quot;Load_0011&quot;: &quot;阿雷斯达王国公主的女仆。\n不仅仅是作为女仆，在护卫方面也具有极高的能力。\n为了调查传说的血族沉睡的「封印的古城」\n发生的异状而从王城出发了。&quot;,
        ///      &quot;Load_0012&quot;: &quot;阿雷斯达王国进行魔法研究的\n女 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadTextJson {
            get {
                return ResourceManager.GetString("LoadTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;LoginBonus_0001&quot;: &quot;已获得&quot;,
        ///      &quot;LoginBonus_0002&quot;: &quot;下回获得 : {0}×{1}&quot;,
        ///      &quot;LoginBonus_0003&quot;: &quot;活动期间 : {0}&quot;,
        ///      &quot;LoginBonus_0004&quot;: &quot;NEXT&quot;
        ///}.
        /// </summary>
        internal static string LoginBonusJson {
            get {
                return ResourceManager.GetString("LoginBonusJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Mail_0001&quot;: &quot;邮件&quot;,
        ///      &quot;Mail_0002&quot;: &quot;礼物&quot;,
        ///      &quot;Mail_0003&quot;: &quot;邀请&quot;,
        ///      &quot;Mail_0025&quot;: &quot;删除&quot;,
        ///      &quot;Mail_0004&quot;: &quot;全部领取&quot;,
        ///      &quot;Mail_0005&quot;: &quot;全部删除&quot;,
        ///      &quot;Mail_0017&quot;: &quot;全部领取吗？&quot;,
        ///      &quot;Mail_0018&quot;: &quot;全部删除吗？&quot;,
        ///      &quot;Mail_0009&quot;: &quot;收取邮件&quot;,
        ///      &quot;Mail_0010&quot;: &quot;删除邮件&quot;,
        ///      &quot;Mail_0011&quot;: &quot;领取全部礼物&quot;,
        ///      &quot;Mail_0012&quot;: &quot;删除全部邮件&quot;,
        ///      &quot;Mail_0015&quot;: &quot;收取{0}吗？&quot;,
        ///      &quot;Mail_0016&quot;: &quot;删除{0}吗？&quot;,
        ///      &quot;Mail_0019&quot;: &quot;没有可收取的邮件&quot;,
        ///      &quot;Mail_0020&quot;: &quot;没有可删除的邮件&quot;,
        ///      &quot;Mail_0006&quot;: &quot;已经领取所有礼物&quot;,
        ///      &quot;Mail_000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailTextJson {
            get {
                return ResourceManager.GetString("MailTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Mission_0001&quot;: &quot;任务&quot;,
        ///      &quot;Mission_0003&quot;: &quot;任务详细内容&quot;,
        ///      &quot;Mission_0002&quot;: &quot;成就&quot;,
        ///      &quot;Mission_0007&quot;: &quot;成就详细内容&quot;,
        ///      &quot;Mission_0008&quot;: &quot;解锁&quot;,
        ///      &quot;Mission_0005&quot;: &quot;解锁新的任务栏&quot;,
        ///      &quot;Mission_0004&quot;: &quot;解锁追加栏&quot;,
        ///      &quot;Mission_0006&quot;: &quot;因已经达到可接受任务的数量上限，购买[ffca45]{0}[-]个追加任务栏吗？&quot;,
        ///      &quot;Mission_0009&quot;: &quot;报酬：&quot;,
        ///      &quot;Mission_0010&quot;: &quot;未达成&quot;,
        ///      &quot;Mission_0011&quot;: &quot;达成率&quot;,
        ///      &quot;Mission_0012&quot;: &quot;完成&quot;,
        ///      &quot;Mission_0013&quot;: &quot;请到任务界面\n领取报酬。&quot;,
        ///      &quot;Mission_0014&quot;: &quot;报酬：{0}ｘ{1}个&quot;,
        ///      &quot;Mission_0015&quot;: &quot;放弃&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MissionTextJson {
            get {
                return ResourceManager.GetString("MissionTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;MyPage_0001&quot;: &quot;主界面&quot;,
        ///      &quot;MyPage_0002&quot;: &quot;单人&quot;,
        ///      &quot;MyPage_0003&quot;: &quot;对战&quot;,
        ///      &quot;MyPage_0004&quot;: &quot;竞技场&quot;,
        ///      &quot;MyPage_0005&quot;: &quot;卡牌&quot;,
        ///      &quot;MyPage_0006&quot;: &quot;商店&quot;,
        ///      &quot;MyPage_0007&quot;: &quot;其它&quot;,
        ///      &quot;MyPage_0008&quot;: &quot;剧情模式&quot;,
        ///      &quot;MyPage_0009&quot;: &quot;练习模式&quot;,
        ///      &quot;MyPage_0010&quot;: &quot;自由匹配&quot;,
        ///      &quot;MyPage_0011&quot;: &quot;天梯匹配&quot;,
        ///      &quot;MyPage_0012&quot;: &quot;私人对战&quot;,
        ///      &quot;MyPage_0013&quot;: &quot;双选模式&quot;,
        ///      &quot;MyPage_0014&quot;: &quot;编辑牌组&quot;,
        ///      &quot;MyPage_0015&quot;: &quot;卡牌一览/制作&quot;,
        ///      &quot;MyPage_0016&quot;: &quot;购买卡包&quot;,
        ///      &quot;MyPage_0017&quot;: &quot;购买礼包&quot;,
        ///      &quot;M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MyPageTextJson {
            get {
                return ResourceManager.GetString("MyPageTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherCode_0005&quot;: &quot;输入兑换码&quot;,
        ///      &quot;OtherCode_0007&quot;: &quot;兑换记录&quot;,
        ///      &quot;OtherCode_0001&quot;: &quot;输入兑换码可以领取特典。\n获得的特典会直接发送至「礼物」内。&quot;,
        ///      &quot;OtherCode_0003&quot;: &quot;※请不要输入“-”&quot;,
        ///      &quot;OtherCode_0004&quot;: &quot;1个兑换码只能使用1次。&quot;,
        ///      &quot;OtherCode_0006&quot;: &quot;标题&quot;,
        ///      &quot;OtherCode_0008&quot;: &quot;领取日期&quot;,
        ///      &quot;OtherCode_0009&quot;: &quot;请输入代码&quot;,
        ///      &quot;OtherCode_0010&quot;: &quot;代码录入完毕。\n获得的礼品会直接发送至「礼物」内。&quot;,
        ///      &quot;OtherCode_0011&quot;: &quot;录入完毕&quot;
        ///}.
        /// </summary>
        internal static string OtherCodeTextJson {
            get {
                return ResourceManager.GetString("OtherCodeTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherConfig_0001&quot;: &quot;音乐&quot;,
        ///      &quot;OtherConfig_0002&quot;: &quot;音效&quot;,
        ///      &quot;OtherConfig_0003&quot;: &quot;语音&quot;,
        ///      &quot;OtherConfig_0004&quot;: &quot;回合结束确认&quot;,
        ///      &quot;OtherConfig_0005&quot;: &quot;显示敌方表情&quot;,
        ///      &quot;OtherConfig_0006&quot;: &quot;开&quot;,
        ///      &quot;OtherConfig_0007&quot;: &quot;关&quot;,
        ///      &quot;OtherConfig_0008&quot;: &quot;开&quot;,
        ///      &quot;OtherConfig_0009&quot;: &quot;关&quot;,
        ///      &quot;OtherConfig_0010&quot;: &quot;简化战斗特效&quot;,
        ///      &quot;OtherConfig_0011&quot;: &quot;固定屏幕方向&quot;,
        ///      &quot;OtherConfig_0012&quot;: &quot;开&quot;,
        ///      &quot;OtherConfig_0013&quot;: &quot;关&quot;,
        ///      &quot;OtherConfig_0014&quot;: &quot;自动播放剧情&quot;,
        ///      &quot;OtherConfig_0015&quot;: &quot;开&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherConfigTextJson {
            get {
                return ResourceManager.GetString("OtherConfigTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherFriend_0001&quot;: &quot;好友&quot;,
        ///      &quot;OtherFriend_0002&quot;: &quot;好友一览&quot;,
        ///      &quot;OtherFriend_0003&quot;: &quot;申请中&quot;,
        ///      &quot;OtherFriend_0004&quot;: &quot;等待通过&quot;,
        ///      &quot;OtherFriend_0005&quot;: &quot;通过&quot;,
        ///      &quot;OtherFriend_0006&quot;: &quot;好友检索&quot;,
        ///      &quot;OtherFriend_0007&quot;: &quot;上次登录时间&quot;,
        ///      &quot;OtherFriend_0008&quot;: &quot;{0}分钟前&quot;,
        ///      &quot;OtherFriend_0009&quot;: &quot;{0}小时前&quot;,
        ///      &quot;OtherFriend_0010&quot;: &quot;{0}天前&quot;,
        ///      &quot;OtherFriend_0011&quot;: &quot;全部取消&quot;,
        ///      &quot;OtherFriend_0012&quot;: &quot;移除&quot;,
        ///      &quot;OtherFriend_0013&quot;: &quot;全部取消&quot;,
        ///      &quot;OtherFriend_0014&quot;: &quot;通过&quot;,
        ///      &quot;OtherFriend_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherFriendTextJson {
            get {
                return ResourceManager.GetString("OtherFriendTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherPassword_0006&quot;: &quot;输入代码&quot;,
        ///      &quot;OtherPassword_0007&quot;: &quot;确定以输入的代码来下载数据吗？&quot;,
        ///      &quot;OtherPassword_0001&quot;: &quot;通过发行代码可以在别的终端进行游玩。&quot;,
        ///      &quot;OtherPassword_0002&quot;: &quot;另外，数据发生破损的时候可以使用代码来使数据恢复。&quot;,
        ///      &quot;OtherPassword_0003&quot;: &quot;按下下面的按钮，可以在此处发行代码。&quot;,
        ///      &quot;OtherPassword_0004&quot;: &quot;注意：现在游戏中的存档数据会被现在输入的数据所覆盖。&quot;,
        ///      &quot;OtherPassword_0005&quot;: &quot;建议您在输入代码之前先保存好现在存档数据的代码。&quot;,
        ///      &quot;OtherPassword_0008&quot;: &quot;发行&quot;
        ///}.
        /// </summary>
        internal static string OtherPasswordTextJson {
            get {
                return ResourceManager.GetString("OtherPasswordTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Profile_0001&quot;: &quot;战绩&quot;,
        ///      &quot;Profile_0002&quot;: &quot;昵称&quot;,
        ///      &quot;Profile_0003&quot;: &quot;称号&quot;,
        ///      &quot;Profile_0004&quot;: &quot;变更徽章&quot;,
        ///      &quot;Profile_0005&quot;: &quot;变更旗帜&quot;,
        ///      &quot;Profile_0006&quot;: &quot;变更称号&quot;,
        ///      &quot;Profile_0007&quot;: &quot;变更昵称&quot;,
        ///      &quot;Profile_0008&quot;: &quot;用户ID&quot;,
        ///      &quot;Profile_0009&quot;: &quot;复制&quot;,
        ///      &quot;Profile_0010&quot;: &quot;对战积分&quot;,
        ///      &quot;Profile_0011&quot;: &quot;NEXT&quot;,
        ///      &quot;Profile_0012&quot;: &quot;等级一览&quot;,
        ///      &quot;Profile_0013&quot;: &quot;职业角色胜利次数&quot;,
        ///      &quot;Profile_0014&quot;: &quot;用户名已变更为\n{0}&quot;,
        ///      &quot;Profile_0015&quot;: &quot;已复制用户ID&quot;,
        ///      &quot;Profile_0016&quot;: &quot;Page&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherProfileTextJson {
            get {
                return ResourceManager.GetString("OtherProfileTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Ranking_0001_Menu&quot;: &quot;对战积分&quot;,
        ///      &quot;Ranking_0001_Header&quot;: &quot;对战积分排行榜&quot;,
        ///      &quot;Ranking_0002_Menu&quot;: &quot;大师级积分&quot;,
        ///      &quot;Ranking_0002_Header&quot;: &quot;大师级积分排行榜&quot;,
        ///      &quot;Ranking_0003_Menu&quot;: &quot;天梯胜场&quot;,
        ///      &quot;Ranking_0003_Header&quot;: &quot;天梯胜场排行榜&quot;,
        ///      &quot;Ranking_0004_Menu&quot;: &quot;竞技场&quot;,
        ///      &quot;Ranking_0004_Header_Old&quot;: &quot;竞技场胜场排行榜&quot;,
        ///      &quot;Ranking_0004_Header_New&quot;: &quot;竞技场5战全胜排行榜&quot;,
        ///      &quot;Ranking_0101&quot;: &quot;胜&quot;,
        ///      &quot;Ranking_0102&quot;: &quot;pt&quot;,
        ///      &quot;Ranking_0103&quot;: &quot;次&quot;,
        ///      &quot;Ranking_0201&quot;: &quot;※战绩需要一定时间才能更新至排行榜。&quot;,
        ///      &quot;Ranking_02 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherRankingTextJson {
            get {
                return ResourceManager.GetString("OtherRankingTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherShareMovie_0001&quot;: &quot;分享游戏录像&quot;
        ///}.
        /// </summary>
        internal static string OtherShareMovieTextJson {
            get {
                return ResourceManager.GetString("OtherShareMovieTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;OtherTop_0001&quot;: &quot;个人信息&quot;,
        ///      &quot;OtherTop_0002&quot;: &quot;排行榜&quot;,
        ///      &quot;OtherTop_0003&quot;: &quot;设定&quot;,
        ///      &quot;OtherTop_0004&quot;: &quot;继承&quot;,
        ///      &quot;OtherTop_0005&quot;: &quot;好友&quot;,
        ///      &quot;OtherTop_0006&quot;: &quot;帮助&quot;,
        ///      &quot;OtherTop_0007&quot;: &quot;咨询&quot;,
        ///      &quot;OtherTop_0009&quot;: &quot;隐私条款&quot;,
        ///      &quot;OtherTop_0009_Update&quot;: &quot;隐私条款(更新)&quot;,
        ///      &quot;OtherTop_0010&quot;: &quot;服务协议&quot;,
        ///      &quot;OtherTop_0010_Update&quot;: &quot;服务协议(更新)&quot;,
        ///      &quot;OtherTop_0012&quot;: &quot;视频录像设定&quot;,
        ///      &quot;OtherTop_0014&quot;: &quot;其它&quot;,
        ///      &quot;OtherTop_0015&quot;: &quot;相关链接&quot;,
        ///      &quot;OtherTop_0017&quot;: &quot;下载数据&quot;,
        ///      &quot;OtherTop_00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherTopTextJson {
            get {
                return ResourceManager.GetString("OtherTopTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Practice_Maintenance&quot;: &quot;※练习模式维护中&quot;,
        ///      &quot;Practice_1001&quot;: &quot;亚里莎 - 初级&quot;,
        ///      &quot;Practice_1002&quot;: &quot;亚里莎 - 中级&quot;,
        ///      &quot;Practice_1003&quot;: &quot;亚里莎 - 高级(1)&quot;,
        ///      &quot;Practice_1004&quot;: &quot;亚里莎 - 高级(2)&quot;,
        ///      &quot;Practice_1005&quot;: &quot;亚里莎 - 超级(1)&quot;,
        ///      &quot;Practice_1006&quot;: &quot;亚里莎 - 超级(2)&quot;,
        ///      &quot;Practice_2001&quot;: &quot;艾莉卡 - 初级&quot;,
        ///      &quot;Practice_2002&quot;: &quot;艾莉卡 - 中级&quot;,
        ///      &quot;Practice_2003&quot;: &quot;艾莉卡 - 高级(1)&quot;,
        ///      &quot;Practice_2004&quot;: &quot;艾莉卡 - 高级(2)&quot;,
        ///      &quot;Practice_2005&quot;: &quot;艾莉卡 - 超级(1)&quot;,
        ///      &quot;Practice_2006&quot;: &quot;艾莉卡 - 超级(2)&quot;,
        ///      &quot;Pra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string practicetextmaster {
            get {
                return ResourceManager.GetString("practicetextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;1&quot;: &quot;青铜&quot;,
        ///      &quot;2&quot;: &quot;白银&quot;,
        ///      &quot;3&quot;: &quot;黄金&quot;,
        ///      &quot;4&quot;: &quot;传说&quot;
        ///}.
        /// </summary>
        internal static string raritynametextmaster {
            get {
                return ResourceManager.GetString("raritynametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;rarity_1&quot;: &quot;青铜&quot;,
        ///      &quot;rarity_2&quot;: &quot;白银&quot;,
        ///      &quot;rarity_3&quot;: &quot;黄金&quot;,
        ///      &quot;rarity_4&quot;: &quot;传说&quot;
        ///}.
        /// </summary>
        internal static string raritytextjson {
            get {
                return ResourceManager.GetString("raritytextjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;RoomBattle_0001&quot;: &quot;私人对战&quot;,
        ///      &quot;RoomBattle_0002&quot;: &quot;创建房间&quot;,
        ///      &quot;RoomBattle_0003&quot;: &quot;进入房间&quot;,
        ///      &quot;RoomBattle_0004&quot;: &quot;观战&quot;,
        ///      &quot;RoomBattle_0005&quot;: &quot;有新的邀请&quot;,
        ///      &quot;RoomBattle_0006&quot;: &quot;输入房间ID&quot;,
        ///      &quot;RoomBattle_0007&quot;: &quot;观战模式未开启&quot;,
        ///      &quot;RoomBattle_0008&quot;: &quot;邀请好友&quot;,
        ///      &quot;RoomBattle_0009&quot;: &quot;房间ID&quot;,
        ///      &quot;RoomBattle_0010&quot;: &quot;聊天&quot;,
        ///      &quot;RoomBattle_0011&quot;: &quot;选择牌组&quot;,
        ///      &quot;RoomBattle_0012&quot;: &quot;未选择牌组\n\n请选择\n使用的牌组&quot;,
        ///      &quot;RoomBattle_0013&quot;: &quot;到关闭房间为止&quot;,
        ///      &quot;RoomBattle_0014&quot;: &quot;15秒内最多只能发送3条信息&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoomBattleTextJson {
            get {
                return ResourceManager.GetString("RoomBattleTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Shop_0001&quot;: &quot;购买卡包&quot;,
        ///      &quot;Shop_0002&quot;: &quot;购买卡背&quot;,
        ///      &quot;Shop_0003&quot;: &quot;购买水晶&quot;,
        ///      &quot;Shop_0004&quot;: &quot;抽取率&quot;,
        ///      &quot;Shop_0005&quot;: &quot;交易通知&quot;,
        ///      &quot;Shop_0006&quot;: &quot;卡包{0}&quot;,
        ///      &quot;Shop_0007&quot;: &quot;卡包信息取得失败。&quot;,
        ///      &quot;Shop_0028&quot;: &quot;卡包兑换券&quot;,
        ///      &quot;Shop_0010&quot;: &quot;获得卡牌&quot;,
        ///      &quot;Shop_0009&quot;: &quot;您今日不能开更多的卡包了。&quot;,
        ///      &quot;Shop_0011&quot;: &quot;取得卡背信息失败。&quot;,
        ///      &quot;Shop_0012&quot;: &quot;点击选择卡背。&quot;,
        ///      &quot;Shop_0014&quot;: &quot;已购买「{0}」卡背。&quot;,
        ///      &quot;Shop_0013&quot;: &quot;水晶不足。\n进入水晶购买画面吗？&quot;,
        ///      &quot;Shop_0015&quot;: &quot;点击后打开&quot;,
        ///      &quot;Shop_0016&quot;: &quot;下一步&quot;,
        ///      &quot;Shop_0025&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShopTextJson {
            get {
                return ResourceManager.GetString("ShopTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;SD_100011010_01&quot;: &quot;&quot;,
        ///      &quot;SD_100011010_02&quot;: &quot;&quot;,
        ///      &quot;SD_100011020_01&quot;: &quot;&quot;,
        ///      &quot;SD_100011020_02&quot;: &quot;&quot;,
        ///      &quot;SD_100011030_01&quot;: &quot;&quot;,
        ///      &quot;SD_100011030_02&quot;: &quot;&quot;,
        ///      &quot;SD_100011040_01&quot;: &quot;&quot;,
        ///      &quot;SD_100011040_02&quot;: &quot;&quot;,
        ///      &quot;SD_100011050_01&quot;: &quot;[u][ffcd45]守护[-][/u]&quot;,
        ///      &quot;SD_100011050_02&quot;: &quot;[u][ffcd45]守护[-][/u]&quot;,
        ///      &quot;SD_100012010&quot;: &quot;己方回合开始时，使1个随机的己方随从获得+1/+1。&quot;,
        ///      &quot;SD_100031010_01&quot;: &quot;[u][ffcd45]攻击时[-][/u] 对敌方英雄造成2点伤害。\n己方回合开始时，和己方场上的1个[u][ffcd45]囚罪双子・琉璃[-][/u]融合为[u][ffcd45 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string skilldesctextmaster {
            get {
                return ResourceManager.GetString("skilldesctextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;SN_スタンダード1&quot;: &quot;标准&quot;,
        ///      &quot;SN_スタンダード2&quot;: &quot;精灵&quot;,
        ///      &quot;SN_スタンダード3&quot;: &quot;皇室护卫&quot;,
        ///      &quot;SN_スタンダード4&quot;: &quot;巫师&quot;,
        ///      &quot;SN_スタンダード5&quot;: &quot;龙&quot;,
        ///      &quot;SN_スタンダード6&quot;: &quot;死灵术士&quot;,
        ///      &quot;SN_スタンダード7&quot;: &quot;血族&quot;,
        ///      &quot;SN_スタンダード8&quot;: &quot;主教&quot;,
        ///      &quot;SN_アリサスリーブ&quot;: &quot;亚里莎&quot;,
        ///      &quot;SN_エリカスリーブ&quot;: &quot;艾莉卡&quot;,
        ///      &quot;SN_イザベルスリーブ&quot;: &quot;伊莎贝尔&quot;,
        ///      &quot;SN_ローウェンスリーブ&quot;: &quot;罗文&quot;,
        ///      &quot;SN_ルナスリーブ&quot;: &quot;露娜&quot;,
        ///      &quot;SN_ユリアススリーブ&quot;: &quot;尤里亚斯&quot;,
        ///      &quot;SN_イリススリーブ&quot;: &quot;伊莉丝&quot;,
        ///      &quot;SN_神撃のバハムート1&quot;: &quot;巴哈姆特之怒(1)&quot;,
        ///      &quot;SN_神撃のバハムート2&quot;: &quot;巴哈姆特之怒(2)&quot;,
        ///      &quot;SN_神撃のバハムート3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sleevenametextmaster {
            get {
                return ResourceManager.GetString("sleevenametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;sleeve_1&quot;: &quot;巴哈姆特之怒(1-2)&quot;,
        ///      &quot;sleeve_2&quot;: &quot;巴哈姆特之怒(3-5)&quot;,
        ///      &quot;sleeve_3&quot;: &quot;卡背(3)&quot;,
        ///      &quot;sleeve_4&quot;: &quot;卡背(4)&quot;,
        ///      &quot;sleeve_5&quot;: &quot;卡背(5)&quot;,
        ///      &quot;sleeve_6&quot;: &quot;卡背(6)&quot;,
        ///      &quot;sleeve_7&quot;: &quot;碧蓝幻想(1-3)&quot;,
        ///      &quot;sleeve_8&quot;: &quot;碧蓝幻想(4-6)&quot;,
        ///      &quot;sleeve_9&quot;: &quot;偶像大师(1-3)&quot;,
        ///      &quot;sleeve_10&quot;: &quot;偶像大师(4-6)&quot;,
        ///      &quot;sleeve_11&quot;: &quot;圣铃天使&quot;,
        ///      &quot;sleeve_12&quot;: &quot;命运之末・乌露德&quot;,
        ///      &quot;sleeve_13&quot;: &quot;雪人&quot;,
        ///      &quot;sleeve_14&quot;: &quot;乙姬护卫队&quot;,
        ///      &quot;sleeve_15&quot;: &quot;艾拉的祈祷&quot;,
        ///      &quot;sleeve_16&quot;: &quot;精灵少女・莉萨&quot;
        ///}.
        /// </summary>
        internal static string sleeveproducttextmaster {
            get {
                return ResourceManager.GetString("sleeveproducttextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;SSN_ファーストシリーズ&quot;: &quot;第一弹&quot;,
        ///      &quot;SSN_セカンドシリーズ&quot;: &quot;第二弹&quot;
        ///}.
        /// </summary>
        internal static string sleeveseriesnametextmaster {
            get {
                return ResourceManager.GetString("sleeveseriesnametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;SSN_ファーストシリーズ&quot;: &quot;第一弹&quot;,
        ///      &quot;SSN_セカンドシリーズ&quot;: &quot;第二弹&quot;,
        ///      &quot;SSN_サードシリーズ&quot;: &quot;第三弹&quot;,
        ///      &quot;SSN_フォースシリーズ&quot;: &quot;第四弹&quot;,
        ///      &quot;SSI_神撃のバハムート&quot;: &quot;收集卡牌组成牌组，在秘银大陆的世界进行冒险的\n集换式卡牌幻想类角色扮演游戏！\n在编辑牌组中可以变更卡背。&quot;,
        ///      &quot;SSI_セカンドシリーズ&quot;: &quot;第二弹介绍&quot;,
        ///      &quot;SSI_サードシリーズ&quot;: &quot;第三弹介绍&quot;,
        ///      &quot;SSI_グランブルーファンタジー&quot;: &quot;在蔚蓝的天空冒险的正统角色扮演游戏！\n战斗中可以使用能造成巨大伤害的「奥义」\n或强力的「星晶兽」，简单的操作就能\n体验华丽的战斗！\n在编辑牌组中可以变更卡背。&quot;,
        ///      &quot;SSI_アイドルマスターシンデレラガールズ&quot;: &quot;即刻领取偶像大师的连动卡背！\n你还在犹豫什么？\n马上拥有她！\n在编辑牌组中可以变更卡背。&quot;,
        ///      &quot;SSI_累積BP報酬&quot;: &quot;2016年10月～12月的累积BP奖励！\n除卡背之外 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sleeveseriestextmaster {
            get {
                return ResourceManager.GetString("sleeveseriestextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Story_0001&quot;: &quot;选择英雄&quot;,
        ///      &quot;Story_0002&quot;: &quot;选择章节&quot;,
        ///      &quot;Story_0013&quot;: &quot;章节 {0}&quot;,
        ///      &quot;Story_0003&quot;: &quot;开始章节 {0}&quot;,
        ///      &quot;Story_0004&quot;: &quot;继续&quot;,
        ///      &quot;Story_0005&quot;: &quot;※请点击&quot;,
        ///      &quot;Story_0006&quot;: &quot;详细&quot;,
        ///      &quot;Story_0011&quot;: &quot;普通&quot;,
        ///      &quot;Story_0012&quot;: &quot;困难&quot;,
        ///      &quot;Story_0024&quot;: &quot;初级&quot;,
        ///      &quot;Story_0025&quot;: &quot;中级&quot;,
        ///      &quot;Story_0026&quot;: &quot;高级(1)&quot;,
        ///      &quot;Story_0034&quot;: &quot;高级(2)&quot;,
        ///      &quot;Story_0033&quot;: &quot;超级&quot;,
        ///      &quot;Story_0014&quot;: &quot;状态：完成&quot;,
        ///      &quot;Story_0015&quot;: &quot;新章节已开放&quot;,
        ///      &quot;Story_0016&quot;: &quot;选择对战对手&quot;,
        ///      &quot;Story_0017 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoryTextJson {
            get {
                return ResourceManager.GetString("StoryTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;ST_chapter_01_01&quot;: &quot;第1章 启程&quot;,
        ///      &quot;ST_chapter_01_02&quot;: &quot;第2章 幽暗森林&quot;,
        ///      &quot;ST_chapter_01_03&quot;: &quot;第3章 通灵少女&quot;,
        ///      &quot;ST_chapter_01_04&quot;: &quot;第4章 黑龙&quot;,
        ///      &quot;ST_chapter_01_05&quot;: &quot;第5章 重要的人&quot;,
        ///      &quot;ST_chapter_01_06&quot;: &quot;第6章 心灵的黑暗&quot;,
        ///      &quot;ST_chapter_01_07&quot;: &quot;第7章 回忆&quot;,
        ///      &quot;ST_chapter_01_08&quot;: &quot;第8章 灾厄之树&quot;,
        ///      &quot;ST_chapter_02_01&quot;: &quot;第1章 王命&quot;,
        ///      &quot;ST_chapter_02_02&quot;: &quot;第2章 邂逅&quot;,
        ///      &quot;ST_chapter_02_03&quot;: &quot;第3章 共振&quot;,
        ///      &quot;ST_chapter_02_04&quot;: &quot;第4章 忧郁的骑士&quot;,
        ///      &quot;ST_chapter_02_05&quot;: &quot;第5章 代价&quot;,
        ///      &quot;ST_chap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string storytextmaster {
            get {
                return ResourceManager.GetString("storytextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;System_TimeDateLong&quot;: &quot;yyyy/MM/dd HH:mm&quot;,
        ///      &quot;System_TimeDateShort&quot;: &quot;MM/dd HH:mm&quot;,
        ///      &quot;System_DateLong&quot;: &quot;yyyy/MM/dd&quot;,
        ///      &quot;System_DateShort&quot;: &quot;MM/dd&quot;,
        ///      &quot;System_Time&quot;: &quot;HH:mm&quot;,
        ///      &quot;System_YearMonth&quot;: &quot;yyyy/MM&quot;,
        ///      &quot;System_Between&quot;: &quot;{0} ～ {1}&quot;,
        ///      &quot;System_LineHeadWrap&quot;: &quot;､、｡。)）］」』}｝】,〕〉＞》≫〟’”.・:; 　!?！？…ー～－☆★♪，‐＝゛゜％/&quot;,
        ///      &quot;System_LineEndWrap&quot;: &quot;(（［{｛〔〈＜《≪「『【〝‘“×+＋/-&quot;,
        ///      &quot;System_0001&quot;: &quot;载入中&quot;,
        ///      &quot;System_0002&quot;: &quot;代码&quot;,
        ///      &quot;System_0003&quot;: &quot;网络连接出错&quot;,
        ///      &quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemTextJson {
            get {
                return ResourceManager.GetString("SystemTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Title_0002&quot;: &quot;请输入用户名&quot;,
        ///      &quot;Title_0001&quot;: &quot;注册用户名&quot;,
        ///      &quot;Title_0003&quot;: &quot;用户名注册完成&quot;,
        ///      &quot;Title_0004&quot;: &quot;用户名:{0}\n注册完成&quot;,
        ///      &quot;Title_0005&quot;: &quot;用户名:{0}\n注册失败。\n请重新注册用户名。&quot;,
        ///      &quot;Title_0006&quot;: &quot;菜单&quot;,
        ///      &quot;Title_0007&quot;: &quot;清除缓存&quot;,
        ///      &quot;Title_0008&quot;: &quot;清除缓存的话可能可以减轻硬件的负担。\n不会删除游戏的存档数据。\n清除缓存后会再次下载相关数据。\n根据网络连接状况，可能会花费较长时间。\n\n确定清除缓存吗？\n[ffcd45]清除缓存会导致正在进行中的对局结算为败北。[-]&quot;,
        ///      &quot;Title_0009&quot;: &quot;缓存已清除。&quot;,
        ///      &quot;Title_0010&quot;: &quot;下载数据&quot;,
        ///      &quot;Title_0011&quot;: &quot;检测到有新的数据。\n请点击确认键进行下载。&quot;,
        ///      &quot;Title_0012&quot;: &quot;数据下 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TitleTextJson {
            get {
                return ResourceManager.GetString("TitleTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;TN_ALL&quot;: &quot;ALL&quot;,
        ///      &quot;TN_兵士&quot;: &quot;士兵&quot;,
        ///      &quot;TN_指揮官&quot;: &quot;指挥官&quot;,
        ///      &quot;TN_土の印&quot;: &quot;土之印&quot;
        ///}.
        /// </summary>
        internal static string tribenametextmaster {
            get {
                return ResourceManager.GetString("tribenametextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;Tutorial_0001&quot;: &quot;萝沙丽亚真厉害！&quot;,
        ///      &quot;Tutorial_0002&quot;: &quot;真开心啊！&quot;,
        ///      &quot;Tutorial_0003&quot;: &quot;教程信息(3)&quot;,
        ///      &quot;Tutorial_0004&quot;: &quot;章节{0}&quot;,
        ///      &quot;Tutorial_0005&quot;: &quot;亚里莎&quot;,
        ///      &quot;Tutorial_0006&quot;: &quot;章节{0}&quot;,
        ///      &quot;Tutorial_0007&quot;: &quot;教程&quot;,
        ///      &quot;Tutorial_0008&quot;: &quot;跳过教程&quot;,
        ///      &quot;Tutorial_0009&quot;: &quot;跳过本场战斗吗？&quot;,
        ///      &quot;Tutorial_0010&quot;: &quot;请先选择单人游戏&quot;
        ///}.
        /// </summary>
        internal static string TutorialTextJson {
            get {
                return ResourceManager.GetString("TutorialTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;TT_Title0001&quot;: &quot;使用卡牌&quot;,
        ///      &quot;TT_Title0002&quot;: &quot;教程&quot;,
        ///      &quot;TT_Title0003&quot;: &quot;攻击&quot;,
        ///      &quot;TT_Title0004&quot;: &quot;守护&quot;,
        ///      &quot;TT_Title0005&quot;: &quot;进化(1)&quot;,
        ///      &quot;TT_Title0006&quot;: &quot;进化(2)&quot;,
        ///      &quot;TT_Title0007&quot;: &quot;结界卡牌(1)&quot;,
        ///      &quot;TT_Title0008&quot;: &quot;结界卡牌(2)&quot;,
        ///      &quot;TT_Title0009&quot;: &quot;咒术卡牌(1)&quot;,
        ///      &quot;TT_Title0010&quot;: &quot;咒术卡牌(2)&quot;,
        ///      &quot;TT_Title0011&quot;: &quot;交换手牌&quot;,
        ///      &quot;TT_Title0012&quot;: &quot;实战&quot;,
        ///      &quot;TT_Title0013&quot;: &quot;教程完成&quot;,
        ///      &quot;TT_Desc0001&quot;: &quot;消费与卡牌的消耗相应的PP(法力值)，可以召唤(使用)卡牌。\n\n向前拖动手牌中的「地精战士」来召唤(使用)它。&quot;,
        ///      &quot;TT_Desc000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tutorialtextmaster {
            get {
                return ResourceManager.GetString("tutorialtextmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;URL_0001&quot;: &quot;https://shadowverse.jp/faq/?fromapp&quot;,
        ///      &quot;URL_0002&quot;: &quot;http://sennatsu.com/&quot;,
        ///      &quot;URL_0003&quot;: &quot;https://shadowverse.jp/&quot;,
        ///      &quot;URL_0012&quot;: &quot;https://shadowverse.jp/gameguide/&quot;,
        ///      &quot;URL_0004_dmm&quot;: &quot;https://dmm.shadowverse.jp/news/&quot;,
        ///      &quot;URL_0005_dmm&quot;: &quot;https://dmm.shadowverse.jp/about/&quot;,
        ///      &quot;URL_0006_dmm&quot;: &quot;https://dmm.shadowverse.jp/copyright/&quot;,
        ///      &quot;URL_0007_dmm&quot;: &quot;https://dmm.shadowverse.jp/privacy/&quot;,
        ///      &quot;URL_0008_dmm&quot;: &quot;https://dmm.shadowverse.jp/fund/&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string URLTextJson {
            get {
                return ResourceManager.GetString("URLTextJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;VideoHosting_0001&quot;: &quot;录影/直播/观看&quot;,
        ///      &quot;VideoHosting_0002&quot;: &quot;录影设定&quot;,
        ///      &quot;VideoHosting_0003&quot;: &quot;NICO直播设定&quot;,
        ///      &quot;VideoHosting_0004&quot;: &quot;发布至NICO视频&quot;,
        ///      &quot;VideoHosting_0005&quot;: &quot;观看NICO视频&quot;,
        ///      &quot;VideoHosting_0006&quot;: &quot;录影模式&quot;,
        ///      &quot;VideoHosting_0007&quot;: &quot;NICO直播/观看&quot;,
        ///      &quot;VideoHosting_0008&quot;: &quot;录影/观看&quot;,
        ///      &quot;VideoHosting_0009&quot;: &quot;直播模式&quot;,
        ///      &quot;VideoHosting_0010&quot;: &quot;开&quot;,
        ///      &quot;VideoHosting_0011&quot;: &quot;关&quot;,
        ///      &quot;VideoHosting_0012&quot;: &quot;NICO视频录影&quot;,
        ///      &quot;VideoHosting_0013&quot;: &quot;显示对战者的用户昵称&quot;,
        ///      &quot;VideoHo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VideoHostingTextJson {
            get {
                return ResourceManager.GetString("VideoHostingTextJson", resourceCulture);
            }
        }
    }
}
